-- One nullable column per built-in type the sql! macro maps to a Rust type,
-- for the type matrix round-trip tests (tests/type_matrix.rs).
CREATE TABLE type_matrix (
    id INT PRIMARY KEY,
    c_bool BOOL,
    c_bytea BYTEA,
    c_char "char",
    c_name NAME,
    c_int2 INT2,
    c_int4 INT4,
    c_int8 INT8,
    c_text TEXT,
    c_varchar VARCHAR(20),
    c_bpchar CHAR(3),
    c_oid OID,
    c_xid XID,
    c_cid CID,
    c_xid8 XID8,
    c_json JSON,
    c_jsonb JSONB,
    c_cidr CIDR,
    c_inet INET,
    c_macaddr MACADDR,
    c_float4 REAL,
    c_float8 DOUBLE PRECISION,
    c_numeric NUMERIC,
    c_date DATE,
    c_time TIME,
    c_timestamp TIMESTAMP,
    c_timestamptz TIMESTAMPTZ,
    c_interval INTERVAL,
    c_timetz TIMETZ,
    c_uuid UUID,
    c_pg_lsn PG_LSN,
    c_regproc REGPROC,
    c_regprocedure REGPROCEDURE,
    c_regoper REGOPER,
    c_regoperator REGOPERATOR,
    c_regclass REGCLASS,
    c_regtype REGTYPE,
    c_regnamespace REGNAMESPACE,
    c_regrole REGROLE,
    c_regcollation REGCOLLATION,
    c_regconfig REGCONFIG,
    c_regdictionary REGDICTIONARY,
    c_int4range INT4RANGE,
    c_int8range INT8RANGE,
    c_numrange NUMRANGE,
    c_daterange DATERANGE,
    c_tsrange TSRANGE,
    c_tstzrange TSTZRANGE,
    c_int4multirange INT4MULTIRANGE,
    c_datemultirange DATEMULTIRANGE
);
