[package]
name = "typedpg_cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "CLI for typedpg migrations"
keywords = ["postgres", "migrations", "cli", "sql"]
categories = ["command-line-utilities", "database"]

[[bin]]
name = "cargo-typedpg"
path = "src/main.rs"
doc = false

[dependencies]
typedpg = { path = "../typedpg", version = "0.4.0" }
typedpg_core = { path = "../typedpg_core", version = "0.4.0" }
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
tokio-postgres = "0.7"
postgres-native-tls = "0.5"
native-tls = "0.2"
chrono = "0.4"
dotenvy = "0.15"

[dev-dependencies]
tempfile = "3"
typedpg_test_support = { path = "../typedpg_test_support" }
