//! Proc macro crate for `typedpg`.
//!
//! This crate provides the [`sql!`] macro, which performs compile-time
//! verification of SQL queries via static analysis. Users should depend on the
//! `typedpg` crate (which re-exports this macro) rather than depending on
//! `typedpg_macros` directly.

extern crate proc_macro;

mod codegen;
mod copy_in_macro;
mod embed_migrations;
mod from_row;
mod migrations_hash;
mod pg_type_map;
mod query_macro;

/// Compile-time verified SQL query with named parameters.
///
/// The `sql!` macro lets you write raw SQL with `$named` parameters and get
/// full compile-time type checking. At build time it reads your migration files,
/// builds a schema snapshot via the DDL interpreter, and statically analyzes
/// every query to ensure column names, parameter types, and result types are all
/// correct. The generated code is fully typed -- no runtime reflection, no
/// stringly-typed access. No Docker required.
///
/// # Syntax
///
/// ```text
/// sql!(executor, "SQL text", param1 = value1, param2 = value2, ...)
/// ```
///
/// The full grammar is:
///
/// ```text
/// sql!(
///     <executor>,
///     "<SQL with $param and $..spread { field1, field2 } placeholders>",
///     [name = expr, ...]
/// )
/// .<method>()
/// .await?
/// ```
///
/// - **executor** -- any expression implementing the `typedpg::Executor`
///   trait (see [Executor types](#executor-types) below).
/// - **SQL string** -- a string literal containing your SQL. Use `$name` for
///   named parameters and `$..name { fields }` for bulk insert spreads.
/// - **param bindings** (optional) -- zero or more `name = expr` pairs.
///   Parameters referenced in the SQL but not explicitly bound are captured
///   from the surrounding scope.
///
/// # Named parameters
///
/// Use `$name` syntax inside the SQL string to reference parameters. The
/// macro rewrites them to PostgreSQL positional placeholders (`$1`, `$2`, ...)
/// automatically.
///
/// ## Explicit assignment
///
/// ```text
/// sql!(pool, "SELECT * FROM users WHERE id = $user_id", user_id = 42)
/// ```
///
/// ## Scope capture
///
/// If a parameter is not explicitly assigned, the macro captures a variable
/// with the same name from the enclosing scope (similar to closures):
///
/// ```text
/// let min_age = 25;
/// let limit = 10;
/// sql!(pool,
///     "SELECT id, name FROM users WHERE age > $min_age LIMIT $limit"
/// )
/// ```
///
/// ## Deduplication
///
/// When the same `$name` appears multiple times in the SQL, it is
/// deduplicated automatically -- only one value is needed:
///
/// ```text
/// sql!(pool,
///     "SELECT * FROM t WHERE a = $x OR b = $x",
///     x = 42
/// )
/// // Generates: ... WHERE a = $1 OR b = $1
/// ```
///
/// # Return methods
///
/// The macro returns a query builder. Call one of these async methods to
/// execute the query:
///
/// | Method              | Return type          | Description                                     |
/// |---------------------|----------------------|-------------------------------------------------|
/// | `.fetch_all()`      | `Vec<Row>`           | Zero or more rows.                              |
/// | `.fetch_one()`      | `Row`                | Exactly one row. Errors if no rows returned.    |
/// | `.fetch_optional()` | `Option<Row>`        | Zero or one row.                                |
/// | `.execute()`        | `u64`                | Number of rows affected (INSERT/UPDATE/DELETE). |
///
/// `Row` is an anonymous struct generated by the macro with typed fields
/// matching the query's output columns. Your editor's autocomplete will show
/// the available fields and their types.
///
/// ```text
/// // fetch_all -- returns Vec<Row>
/// let users = sql!(pool,
///     "SELECT id, name, email FROM users WHERE age > $min_age",
///     min_age = 25
/// ).fetch_all().await?;
/// // users: Vec<{ id: i64, name: String, email: String }>
///
/// // fetch_one -- returns Row, errors if no rows
/// let user = sql!(pool,
///     "SELECT id, name FROM users WHERE id = $user_id",
///     user_id = 1_i64
/// ).fetch_one().await?;
///
/// // fetch_optional -- returns Option<Row>
/// let maybe_user = sql!(pool,
///     "SELECT id, name FROM users WHERE email = $email",
///     email = "alice@example.com"
/// ).fetch_optional().await?;
///
/// // execute -- returns u64 rows affected
/// let deleted = sql!(pool,
///     "DELETE FROM orders WHERE user_id = $user_id AND total_cents = 0",
///     user_id = 1_i64
/// ).execute().await?;
/// ```
///
/// # Bulk insert with `$..spread`
///
/// The `$..var { field1, field2 }` syntax expands an iterable into multiple
/// `VALUES` rows for bulk inserts. Field mapping is mandatory so the macro
/// knows which struct fields map to which columns.
///
/// ```text
/// let new_users = vec![
///     NewUser { name: "Alice".into(), email: "alice@x.com".into(), age: 30 },
///     NewUser { name: "Bob".into(),   email: "bob@x.com".into(),   age: 25 },
/// ];
///
/// let inserted = sql!(pool,
///     "INSERT INTO users (name, email, age)
///      VALUES $..new_users { name, email, age }
///      RETURNING id, name"
/// ).fetch_all().await?;
/// // Generates: VALUES ($1,$2,$3), ($4,$5,$6)
/// // inserted: Vec<{ id: i64, name: String }>
/// ```
///
/// You can select a subset of fields or reorder them:
///
/// ```text
/// // Only insert name and email (age gets DEFAULT)
/// sql!(pool,
///     "INSERT INTO users (name, email) VALUES $..new_users { name, email }"
/// ).execute().await?;
/// ```
///
/// Multiple spreads are supported (e.g. in CTEs):
///
/// ```text
/// sql!(pool,
///     "WITH a AS (INSERT INTO t1 VALUES $..items_a { x, y } RETURNING id),
///          b AS (INSERT INTO t2 VALUES $..items_b { z } RETURNING id)
///      SELECT * FROM a, b"
/// ).fetch_all().await?;
/// ```
///
/// # Domain types (JSONB)
///
/// Columns defined with `CREATE DOMAIN ... AS JSONB` are automatically
/// deserialized into the corresponding Rust struct, and parameters with
/// domain types are automatically serialized. The mapping is configured in
/// your `Cargo.toml`:
///
/// ```text
/// [package.metadata.typedpg.domains]
/// user_preferences = "crate::domains::UserPreferences"
/// order_metadata = "crate::domains::OrderMetadata"
/// ```
///
/// With this configuration, reading a `user_preferences` column returns a
/// `UserPreferences` struct directly, and passing a `UserPreferences` value
/// as a parameter serializes it to JSONB automatically:
///
/// ```text
/// // Reading: preferences is deserialized to UserPreferences
/// let user = sql!(pool,
///     "SELECT id, preferences FROM users WHERE id = $id",
///     id = 1_i64
/// ).fetch_one().await?;
/// println!("theme: {}", user.preferences.theme);
///
/// // Writing: prefs is serialized to JSONB automatically
/// let prefs = UserPreferences { theme: "dark".into(), locale: "en".into(), notifications: true };
/// sql!(pool,
///     "UPDATE users SET preferences = $prefs WHERE id = $user_id",
///     user_id = 1_i64
/// ).execute().await?;
/// ```
///
/// The Rust struct must implement `serde::Serialize` (for parameters) and/or
/// `serde::Deserialize` (for output columns).
///
/// # Executor types
///
/// The first argument to `sql!` can be any type implementing
/// `typedpg::Executor`:
///
/// - `deadpool_postgres::Pool` (or `&Pool`)
/// - `deadpool_postgres::Object` (a checked-out connection)
/// - `tokio_postgres::Client`
/// - `tokio_postgres::Transaction<'_>`
///
/// This means you can pass a pool for simple queries, or a transaction when
/// you need atomicity:
///
/// ```text
/// let tx = pool.begin().await?;
/// sql!(tx, "INSERT INTO orders (...) VALUES (...)").execute().await?;
/// sql!(tx, "UPDATE users SET ...").execute().await?;
/// tx.commit().await?;
/// ```
///
/// # Compile-time behavior
///
/// When you run `cargo build`, each `sql!` invocation triggers the
/// following pipeline:
///
/// 1. **Configuration** -- reads `[package.metadata.typedpg]` from your
///    `Cargo.toml` to find migration paths and domain mappings.
/// 2. **DDL interpretation** -- parses your migration SQL files and builds an
///    in-memory schema snapshot (types, tables, functions, operators).
/// 3. **Static analysis** -- the SQL is parsed and analyzed against the
///    snapshot to determine parameter types, output column types, and
///    nullability.
/// 4. **Code generation** -- an anonymous output struct and a typed query
///    builder are generated as Rust code.
///
/// # Compile-time errors
///
/// The macro produces clear compile-time errors when something is wrong:
///
/// ```text
/// // Invalid column name (PG's wording, plus a snippet pointing at the SQL)
/// sql!(pool, "SELECT nonexistent FROM users").fetch_all().await?;
/// // error: column "nonexistent" does not exist
///
/// // Type mismatch: `age` is an INT column, so `$age` binds an `i32`
/// let age: &str = "not a number";
/// sql!(pool, "SELECT id FROM users WHERE age > $age").fetch_all().await?;
/// // error[E0277]: the trait bound `i32: From<&str>` is not satisfied
///
/// // Missing field mapping on spread
/// sql!(pool, "INSERT INTO users (name, email) VALUES $..items");
/// // error: spread `$..items` needs a field list naming the item fields to bind,
/// //        e.g. `$..items { field1, field2 }`
/// ```
///
/// The `typedpg_compile_fail` crate in the repository pins the exact output
/// of every error the macros report.
#[proc_macro]
pub fn sql(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input = syn::parse_macro_input!(input as query_macro::QueryInput);
    match query_macro::expand(input) {
        Ok(ts) => ts.into(),
        Err(e) => error_placeholder(e).into(),
    }
}

/// Build the token stream returned by `sql!` when analysis fails.
///
/// The naive approach — `e.to_compile_error()` alone — expands to
/// `::core::compile_error!("...")`. Rust-analyzer's hover on the failing
/// `sql!(...)` then follows that expansion into `core` and shows the
/// docs for the `core` crate itself, which is useless to the user.
///
/// To keep IDE support meaningful, we emit a stub block with the same
/// shape as the normal `sql!` expansion: a `__sql_output` struct and a
/// `__typedpg_query` builder with all the usual `fetch_*` /
/// `execute` / `fetch_*_as` methods. Their bodies are `unreachable!()` —
/// the build fails on the preceding `compile_error!`, so they are never
/// run. With this stub:
///
/// 1. `compile_error!` still fires; the user sees the SQL error.
/// 2. Hover on `sql!(...)` lands on the stub builder (defined in the
///    expansion site), not on `core::compile_error!`.
/// 3. Chained `.fetch_one().await?` etc. type-check enough for the IDE
///    to keep going past the failed `sql!`, so secondary diagnostics
///    (e.g. `user.id`) are about the missing field, not about a
///    type-annotation failure that masks the real error.
///
/// The stub's `__sql_output` has no fields, so `user.field` on a failing
/// query will surface as an unknown-field error. That's an acceptable
/// secondary symptom — the user is going to fix the SQL, and the field
/// errors evaporate once the macro succeeds again.
fn error_placeholder(e: syn::Error) -> proc_macro2::TokenStream {
    let compile_err = e.to_compile_error();
    quote::quote! {
        {
            #compile_err

            #[allow(non_camel_case_types, dead_code)]
            struct __sql_output;

            #[allow(non_camel_case_types)]
            struct __typedpg_query<__E: typedpg::Executor>(
                ::std::marker::PhantomData<__E>,
            );

            #[allow(dead_code, unused_variables, clippy::unused_async)]
            impl<__E: typedpg::Executor> __typedpg_query<__E> {
                async fn fetch_all(
                    self,
                ) -> ::std::result::Result<::std::vec::Vec<__sql_output>, typedpg::Error> {
                    ::std::unreachable!()
                }
                async fn fetch_one(
                    self,
                ) -> ::std::result::Result<__sql_output, typedpg::Error> {
                    ::std::unreachable!()
                }
                async fn fetch_optional(
                    self,
                ) -> ::std::result::Result<::std::option::Option<__sql_output>, typedpg::Error>
                {
                    ::std::unreachable!()
                }
                async fn execute(self) -> ::std::result::Result<u64, typedpg::Error> {
                    ::std::unreachable!()
                }
                async fn fetch_stream(
                    self,
                ) -> ::std::result::Result<typedpg::QueryStream<__sql_output>, typedpg::Error> {
                    ::std::unreachable!()
                }
                async fn fetch_stream_as<__T: typedpg::FromRow>(
                    self,
                ) -> ::std::result::Result<typedpg::QueryStream<__T>, typedpg::Error> {
                    ::std::unreachable!()
                }
                async fn fetch_value<__T>(self) -> ::std::result::Result<__T, typedpg::Error> {
                    ::std::unreachable!()
                }
                async fn fetch_all_as<__T: typedpg::FromRow>(
                    self,
                ) -> ::std::result::Result<::std::vec::Vec<__T>, typedpg::Error> {
                    ::std::unreachable!()
                }
                async fn fetch_one_as<__T: typedpg::FromRow>(
                    self,
                ) -> ::std::result::Result<__T, typedpg::Error> {
                    ::std::unreachable!()
                }
                async fn fetch_optional_as<__T: typedpg::FromRow>(
                    self,
                ) -> ::std::result::Result<::std::option::Option<__T>, typedpg::Error>
                {
                    ::std::unreachable!()
                }
            }

            __typedpg_query::<_>(::std::marker::PhantomData)
        }
    }
}

/// Derive macro for `typedpg::FromRow`.
///
/// Generates an implementation that constructs the struct from a
/// `tokio_postgres::Row` by extracting each field by column name.
///
/// ```rust,ignore
/// #[derive(typedpg::FromRow)]
/// struct User {
///     id: i64,
///     name: String,
///     email: Option<String>,
/// }
/// ```
/// Bake a `typedpg::migrate::MigrationSource` from a directory of
/// `NNNN_description.sql` files into the binary at compile time.
///
/// The path is resolved relative to the invoking crate's `CARGO_MANIFEST_DIR`,
/// the same way `include_str!` does. Each migration's contents land in the
/// final binary as a `&'static str` — no filesystem I/O at runtime, and
/// changes to the SQL files re-trigger a rebuild via `include_str!`'s
/// dependency tracking.
///
/// ```rust,ignore
/// let source = typedpg::embed_migrations!("./migrations");
/// let applied = typedpg::migrate::run(&mut client, &source, &config).await?;
/// ```
///
/// Errors at expansion time when:
/// - The path doesn't resolve to a directory.
/// - A `.sql` filename doesn't match `NNNN_description.sql`.
#[proc_macro]
pub fn embed_migrations(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input = syn::parse_macro_input!(input as embed_migrations::EmbedInput);
    match embed_migrations::expand(input) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

/// Bulk-load rows into a table with a binary `COPY ... FROM STDIN`.
///
/// ```rust,ignore
/// let copied: u64 = copy_in!(pool, "users (name, email)", users { name, email }).await?;
/// ```
///
/// - The target is a table (or a partitioned table, or a view with an
///   `INSTEAD OF INSERT` trigger) and an optional column list; without one,
///   every column but the generated ones. It is checked against the schema
///   your migrations build, with PostgreSQL's errors.
/// - The rows are any `IntoIterator` (a `Vec`, a slice, an iterator over
///   anything); each item supplies the listed fields, in the columns'
///   order, with the types the columns require (`Option<T>` only for a
///   nullable column). Items are converted one at a time as the COPY
///   consumes them.
/// - It evaluates to a future of the number of rows copied. On error the
///   COPY is aborted and no row is kept.
///
/// Accepts the same `db = name,` prefix as [`sql!`].
#[proc_macro]
pub fn copy_in(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input = syn::parse_macro_input!(input as copy_in_macro::CopyInInput);
    match copy_in_macro::expand(input) {
        Ok(ts) => ts.into(),
        Err(e) => {
            // The error, plus a future of the right type so `.await?` at the
            // call site adds no errors of its own.
            let err = e.to_compile_error();
            quote::quote! {
                {
                    #err;
                    async { ::std::result::Result::<u64, typedpg::Error>::Ok(::std::unreachable!()) }
                }
            }
            .into()
        }
    }
}

#[proc_macro_derive(FromRow)]
pub fn derive_from_row(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input = syn::parse_macro_input!(input as syn::DeriveInput);
    match from_row::expand(input) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}
