//! Which `pg_catalog` routines can return NULL — the tables behind
//! [`crate::functions::builtin_result_nullable`].
//!
//! Keys are signatures as `proname(typname,…)` over the declared
//! `proargtypes` (`lower(anyrange)`, `int4(jsonb)`): nullability is a
//! property of one overload, not of a name — `lower(text)` never returns
//! NULL, `lower(anyrange)` does for an empty range.
//!
//! Derived mechanically from the PostgreSQL 18.6 sources, not by hand:
//! every `pg_catalog` function of `pg_proc` (kind `f`/`w`, excluding type
//! I/O and `internal`/`cstring`/handler signatures) was mapped through
//! `prosrc` to its C implementation, whose body was scanned for a
//! *reachable* NULL return — `PG_RETURN_NULL()`, `fcinfo->isnull = true`,
//! `SRF_RETURN_NEXT_NULL`, a `nulls[i] = true` result slot — or a call
//! forwarding `fcinfo` to a function that has one. NULL returns right
//! after `ereport(ERROR)`/`elog(ERROR)`/an `*_error()` call, or reached only
//! through an input function's soft-error context, are dead code for a SQL
//! call and don't count; a *local* `ErrorSaveContext` (`to_regclass`) does.
//! Macro-stamped functions (`PG_STAT_GET_RELENTRY_TIMESTAMPTZ(…)`) were
//! expanded first. The SQL-language builtins were classified from their
//! bodies: a scalar subquery (`obj_description`) or a call to a nullable
//! builtin (`pg_relation_size(regclass)`) makes them nullable. The audited
//! cases were confirmed on a live PostgreSQL 18 (`lower('empty'::int4range)`,
//! `to_regclass('nope')`, `current_setting('x.y', true)`, …).
//!
//! Regenerate the same way when moving to a new PostgreSQL major.

/// Strict functions that can return NULL even when every argument is
/// non-NULL. Any other strict `pg_catalog` function returns NULL exactly
/// when an argument is NULL.
pub(crate) const NULLABLE_STRICT: &[&str] = &[
    "area(path)",
    "array_dims(anyarray)",
    "array_length(anyarray,int4)",
    "array_lower(anyarray,int4)",
    "array_ndims(anyarray)",
    "array_upper(anyarray,int4)",
    "bool(jsonb)",
    "box_intersect(box,box)",
    "close_ls(line,lseg)",
    "close_lseg(lseg,lseg)",
    "close_pb(point,box)",
    "close_pl(point,line)",
    "close_ps(point,lseg)",
    "close_sb(lseg,box)",
    "col_description(oid,int4)",
    "current_schema()",
    "current_setting(text,bool)",
    "date_part(text,date)",
    "date_part(text,interval)",
    "date_part(text,timestamp)",
    "date_part(text,timestamptz)",
    "extract(text,date)",
    "extract(text,interval)",
    "extract(text,timestamp)",
    "extract(text,timestamptz)",
    "float4(jsonb)",
    "float8(jsonb)",
    "float8_avg(_float8)",
    "float8_corr(_float8)",
    "float8_covar_pop(_float8)",
    "float8_covar_samp(_float8)",
    "float8_regr_avgx(_float8)",
    "float8_regr_avgy(_float8)",
    "float8_regr_intercept(_float8)",
    "float8_regr_r2(_float8)",
    "float8_regr_slope(_float8)",
    "float8_regr_sxx(_float8)",
    "float8_regr_sxy(_float8)",
    "float8_regr_syy(_float8)",
    "float8_stddev_pop(_float8)",
    "float8_stddev_samp(_float8)",
    "float8_var_pop(_float8)",
    "float8_var_samp(_float8)",
    "has_any_column_privilege(name,oid,text)",
    "has_any_column_privilege(oid,oid,text)",
    "has_any_column_privilege(oid,text)",
    "has_column_privilege(name,oid,int2,text)",
    "has_column_privilege(name,oid,text,text)",
    "has_column_privilege(name,text,int2,text)",
    "has_column_privilege(name,text,text,text)",
    "has_column_privilege(oid,int2,text)",
    "has_column_privilege(oid,oid,int2,text)",
    "has_column_privilege(oid,oid,text,text)",
    "has_column_privilege(oid,text,int2,text)",
    "has_column_privilege(oid,text,text)",
    "has_column_privilege(oid,text,text,text)",
    "has_column_privilege(text,int2,text)",
    "has_column_privilege(text,text,text)",
    "has_database_privilege(name,oid,text)",
    "has_database_privilege(oid,oid,text)",
    "has_database_privilege(oid,text)",
    "has_foreign_data_wrapper_privilege(name,oid,text)",
    "has_foreign_data_wrapper_privilege(oid,oid,text)",
    "has_foreign_data_wrapper_privilege(oid,text)",
    "has_function_privilege(name,oid,text)",
    "has_function_privilege(oid,oid,text)",
    "has_function_privilege(oid,text)",
    "has_language_privilege(name,oid,text)",
    "has_language_privilege(oid,oid,text)",
    "has_language_privilege(oid,text)",
    "has_largeobject_privilege(name,oid,text)",
    "has_largeobject_privilege(oid,oid,text)",
    "has_largeobject_privilege(oid,text)",
    "has_schema_privilege(name,oid,text)",
    "has_schema_privilege(oid,oid,text)",
    "has_schema_privilege(oid,text)",
    "has_sequence_privilege(name,oid,text)",
    "has_sequence_privilege(oid,oid,text)",
    "has_sequence_privilege(oid,text)",
    "has_server_privilege(name,oid,text)",
    "has_server_privilege(oid,oid,text)",
    "has_server_privilege(oid,text)",
    "has_table_privilege(name,oid,text)",
    "has_table_privilege(oid,oid,text)",
    "has_table_privilege(oid,text)",
    "has_tablespace_privilege(name,oid,text)",
    "has_tablespace_privilege(oid,oid,text)",
    "has_tablespace_privilege(oid,text)",
    "has_type_privilege(name,oid,text)",
    "has_type_privilege(oid,oid,text)",
    "has_type_privilege(oid,text)",
    "icu_unicode_version()",
    "int2(jsonb)",
    "int2int4_sum(_int8)",
    "int4(jsonb)",
    "int8(jsonb)",
    "int8_avg(_int8)",
    "json_array_element(json,int4)",
    "json_array_element_text(json,int4)",
    "json_array_elements(json)",
    "json_array_elements_text(json)",
    "json_each(json)",
    "json_each_text(json)",
    "json_extract_path(json,_text)",
    "json_extract_path_text(json,_text)",
    "json_object_field(json,text)",
    "json_object_field_text(json,text)",
    "json_to_record(json)",
    "jsonb_array_element(jsonb,int4)",
    "jsonb_array_element_text(jsonb,int4)",
    "jsonb_array_elements(jsonb)",
    "jsonb_array_elements_text(jsonb)",
    "jsonb_each(jsonb)",
    "jsonb_each_text(jsonb)",
    "jsonb_extract_path(jsonb,_text)",
    "jsonb_extract_path_text(jsonb,_text)",
    "jsonb_object_field(jsonb,text)",
    "jsonb_object_field_text(jsonb,text)",
    // jsonb_path_exists_internal: PG_RETURN_NULL() on a suppressed error.
    "jsonb_path_exists(jsonb,jsonpath,jsonb,bool)",
    "jsonb_path_exists_opr(jsonb,jsonpath)",
    "jsonb_path_exists_tz(jsonb,jsonpath,jsonb,bool)",
    "jsonb_path_match(jsonb,jsonpath,jsonb,bool)",
    "jsonb_path_match_opr(jsonb,jsonpath)",
    "jsonb_path_match_tz(jsonb,jsonpath,jsonb,bool)",
    "jsonb_path_query_first(jsonb,jsonpath,jsonb,bool)",
    "jsonb_path_query_first_tz(jsonb,jsonpath,jsonb,bool)",
    "jsonb_to_record(jsonb)",
    "line_interpt(line,line)",
    "lower(anymultirange)",
    "lower(anyrange)",
    "lseg_interpt(lseg,lseg)",
    "min_scale(numeric)",
    "numeric(jsonb)",
    "obj_description(oid)",
    "obj_description(oid,name)",
    "path_add(path,path)",
    "path_distance(path,path)",
    "pg_available_extensions()",
    "pg_basetype(regtype)",
    "pg_collation_actual_version(oid)",
    "pg_collation_is_visible(oid)",
    "pg_column_compression(any)",
    "pg_column_toast_chunk_id(any)",
    "pg_conversion_is_visible(oid)",
    "pg_copy_logical_replication_slot(name,name)",
    "pg_copy_logical_replication_slot(name,name,bool)",
    "pg_copy_logical_replication_slot(name,name,bool,name)",
    "pg_copy_physical_replication_slot(name,name)",
    "pg_copy_physical_replication_slot(name,name,bool)",
    "pg_create_physical_replication_slot(name,bool,bool)",
    "pg_current_xact_id_if_assigned()",
    "pg_database_collation_actual_version(oid)",
    "pg_database_size(name)",
    "pg_database_size(oid)",
    "pg_describe_object(oid,oid,int4)",
    "pg_encoding_max_length(int4)",
    "pg_event_trigger_ddl_commands()",
    "pg_event_trigger_dropped_objects()",
    "pg_extension_update_paths(name)",
    "pg_filenode_relation(oid,oid)",
    "pg_function_is_visible(oid)",
    "pg_get_acl(oid,oid,int4)",
    "pg_get_aios()",
    "pg_get_constraintdef(oid)",
    "pg_get_constraintdef(oid,bool)",
    "pg_get_expr(pg_node_tree,oid)",
    "pg_get_expr(pg_node_tree,oid,bool)",
    "pg_get_function_arg_default(oid,int4)",
    "pg_get_function_arguments(oid)",
    "pg_get_function_identity_arguments(oid)",
    "pg_get_function_result(oid)",
    "pg_get_function_sqlbody(oid)",
    "pg_get_functiondef(oid)",
    "pg_get_indexdef(oid)",
    "pg_get_indexdef(oid,int4,bool)",
    "pg_get_loaded_modules()",
    "pg_get_partition_constraintdef(oid)",
    "pg_get_partkeydef(oid)",
    "pg_get_publication_tables(_text)",
    "pg_get_replica_identity_index(regclass)",
    "pg_get_ruledef(oid)",
    "pg_get_ruledef(oid,bool)",
    "pg_get_serial_sequence(text,text)",
    "pg_get_shmem_allocations()",
    "pg_get_shmem_allocations_numa()",
    "pg_get_statisticsobjdef(oid)",
    "pg_get_statisticsobjdef_columns(oid)",
    "pg_get_statisticsobjdef_expressions(oid)",
    "pg_get_triggerdef(oid)",
    "pg_get_triggerdef(oid,bool)",
    "pg_get_viewdef(oid)",
    "pg_get_viewdef(oid,bool)",
    "pg_get_viewdef(oid,int4)",
    "pg_get_viewdef(text)",
    "pg_get_viewdef(text,bool)",
    "pg_get_wal_summarizer_state()",
    "pg_hba_file_rules()",
    "pg_ident_file_mappings()",
    "pg_identify_object(oid,oid,int4)",
    "pg_identify_object_as_address(oid,oid,int4)",
    "pg_index_column_has_property(regclass,int4,text)",
    "pg_index_has_property(regclass,text)",
    "pg_indexam_has_property(oid,text)",
    "pg_indexam_progress_phasename(oid,int8)",
    "pg_indexes_size(regclass)",
    "pg_input_error_info(text,text)",
    "pg_last_wal_receive_lsn()",
    "pg_last_wal_replay_lsn()",
    "pg_last_xact_replay_timestamp()",
    "pg_lock_status()",
    "pg_opclass_is_visible(oid)",
    "pg_operator_is_visible(oid)",
    "pg_opfamily_is_visible(oid)",
    "pg_options_to_table(_text)",
    "pg_partition_root(regclass)",
    "pg_partition_tree(regclass)",
    "pg_prepared_statement()",
    "pg_read_binary_file(text)",
    "pg_read_binary_file(text,bool)",
    "pg_read_binary_file(text,int8,int8)",
    "pg_read_binary_file(text,int8,int8,bool)",
    "pg_read_file(text)",
    "pg_read_file(text,bool)",
    "pg_read_file(text,int8,int8)",
    "pg_read_file(text,int8,int8,bool)",
    "pg_relation_filenode(regclass)",
    "pg_relation_filepath(regclass)",
    "pg_relation_is_publishable(regclass)",
    "pg_relation_size(regclass)",
    "pg_relation_size(regclass,text)",
    "pg_replication_origin_oid(text)",
    "pg_replication_origin_progress(text,bool)",
    "pg_replication_origin_session_progress(bool)",
    "pg_sequence_last_value(regclass)",
    "pg_settings_get_flags(text)",
    "pg_show_all_file_settings()",
    "pg_stat_file(text)",
    "pg_stat_file(text,bool)",
    "pg_stat_get_backend_activity_start(int4)",
    "pg_stat_get_backend_client_addr(int4)",
    "pg_stat_get_backend_client_port(int4)",
    "pg_stat_get_backend_dbid(int4)",
    "pg_stat_get_backend_pid(int4)",
    "pg_stat_get_backend_start(int4)",
    "pg_stat_get_backend_subxact(int4)",
    "pg_stat_get_backend_userid(int4)",
    "pg_stat_get_backend_wait_event(int4)",
    "pg_stat_get_backend_wait_event_type(int4)",
    "pg_stat_get_backend_wal(int4)",
    "pg_stat_get_backend_xact_start(int4)",
    "pg_stat_get_db_checksum_failures(oid)",
    "pg_stat_get_db_checksum_last_failure(oid)",
    "pg_stat_get_db_stat_reset_time(oid)",
    "pg_stat_get_function_calls(oid)",
    "pg_stat_get_function_self_time(oid)",
    "pg_stat_get_function_total_time(oid)",
    "pg_stat_get_last_analyze_time(oid)",
    "pg_stat_get_last_autoanalyze_time(oid)",
    "pg_stat_get_last_autovacuum_time(oid)",
    "pg_stat_get_last_vacuum_time(oid)",
    "pg_stat_get_lastscan(oid)",
    "pg_stat_get_progress_info(text)",
    "pg_stat_get_replication_slot(text)",
    "pg_stat_get_snapshot_timestamp()",
    "pg_stat_get_subscription_stats(oid)",
    "pg_stat_get_xact_function_calls(oid)",
    "pg_stat_get_xact_function_self_time(oid)",
    "pg_stat_get_xact_function_total_time(oid)",
    "pg_statistics_obj_is_visible(oid)",
    "pg_table_is_visible(oid)",
    "pg_table_size(regclass)",
    "pg_tablespace_size(name)",
    "pg_tablespace_size(oid)",
    "pg_total_relation_size(regclass)",
    "pg_ts_config_is_visible(oid)",
    "pg_ts_dict_is_visible(oid)",
    "pg_ts_parser_is_visible(oid)",
    "pg_ts_template_is_visible(oid)",
    "pg_type_is_visible(oid)",
    "pg_xact_commit_timestamp(xid)",
    "pg_xact_status(xid8)",
    "poly_distance(polygon,polygon)",
    "range_minus(anyrange,anyrange)",
    "regexp_match(text,text)",
    "regexp_match(text,text,text)",
    "regexp_substr(text,text)",
    "regexp_substr(text,text,int4)",
    "regexp_substr(text,text,int4,int4)",
    "regexp_substr(text,text,int4,int4,text)",
    "regexp_substr(text,text,int4,int4,text,int4)",
    "scale(numeric)",
    "shobj_description(oid,name)",
    "substring(text,text)",
    "substring(text,text,text)",
    "system_user()",
    "time(timestamp)",
    "time(timestamptz)",
    "timetz(timestamptz)",
    "to_char(interval,text)",
    "to_char(timestamp,text)",
    "to_char(timestamptz,text)",
    "to_number(text,text)",
    "to_regclass(text)",
    "to_regcollation(text)",
    "to_regnamespace(text)",
    "to_regoper(text)",
    "to_regoperator(text)",
    "to_regproc(text)",
    "to_regprocedure(text)",
    "to_regrole(text)",
    "to_regtype(text)",
    "to_regtypemod(text)",
    "ts_lexize(regdictionary,text)",
    "txid_current_if_assigned()",
    "txid_status(int8)",
    "unnest(tsvector)",
    "upper(anymultirange)",
    "upper(anyrange)",
    "uuid_extract_timestamp(uuid)",
    "uuid_extract_version(uuid)",
];

/// Non-strict functions that never return NULL, whatever their arguments.
pub(crate) const NEVER_NULL_NONSTRICT: &[&str] = &[
    "array_append(anycompatiblearray,anycompatible)",
    "array_fill(anyelement,_int4)",
    "array_fill(anyelement,_int4,_int4)",
    "array_prepend(anycompatible,anycompatiblearray)",
    "cume_dist()",
    "daterange(date,date)",
    "daterange(date,date,text)",
    "dense_rank()",
    "enum_first(anyenum)",
    "enum_last(anyenum)",
    "enum_range(anyenum)",
    "enum_range(anyenum,anyenum)",
    "int4range(int4,int4)",
    "int4range(int4,int4,text)",
    "int8range(int8,int8)",
    "int8range(int8,int8,text)",
    "json_build_array()",
    "json_build_object()",
    "jsonb_build_array()",
    "jsonb_build_object()",
    "numrange(numeric,numeric)",
    "numrange(numeric,numeric,text)",
    "percent_rank()",
    "pg_logical_slot_get_binary_changes(name,pg_lsn,int4,_text)",
    "pg_logical_slot_get_changes(name,pg_lsn,int4,_text)",
    "pg_logical_slot_peek_binary_changes(name,pg_lsn,int4,_text)",
    "pg_logical_slot_peek_changes(name,pg_lsn,int4,_text)",
    "pg_restore_attribute_stats(any)",
    "pg_restore_relation_stats(any)",
    "pg_show_replication_origin_status()",
    "pg_stat_get_slru()",
    "pg_stat_get_wal()",
    "pg_typeof(any)",
    "quote_nullable(text)",
    "rank()",
    "row_number()",
    "satisfies_hash_partition(oid,int4,int4,any)",
    "set_config(text,text,bool)",
    "string_to_table(text,text)",
    "string_to_table(text,text,text)",
    "tsrange(timestamp,timestamp)",
    "tsrange(timestamp,timestamp,text)",
    "tstzrange(timestamptz,timestamptz)",
    "tstzrange(timestamptz,timestamptz,text)",
];

/// Non-strict functions whose only NULL returns are guarded by a NULL
/// argument (`format(NULL)`, `array_cat(NULL, NULL)`): non-NULL arguments
/// give a non-NULL result.
pub(crate) const NULL_ONLY_ON_NULL_ARG: &[&str] = &[
    "array_cat(anycompatiblearray,anycompatiblearray)",
    "array_positions(anycompatiblearray,anycompatible)",
    "array_remove(anycompatiblearray,anycompatible)",
    "array_replace(anycompatiblearray,anycompatible,anycompatible)",
    "array_to_string(anyarray,text,text)",
    "format(text)",
    "format(text,any)",
    "format_type(oid,int4)",
    "int2_sum(int8,int2)",
    "int4_sum(int8,int4)",
    "int8_sum(numeric,int8)",
    "jsonb_set_lax(jsonb,_text,jsonb,bool,text)",
    "similar_escape(text,text)",
    "xmlconcat2(xml,xml)",
];

/// `VARIADIC "any"` functions that return NULL only for an explicit
/// `VARIADIC NULL` array (`extract_variadic_args` reports no arguments):
/// `concat(VARIADIC NULL::text[])` is NULL, `concat(NULL)` is `''`.
pub(crate) const NULL_ONLY_ON_VARIADIC_NULL: &[&str] = &[
    "concat(any)",
    "json_build_array(any)",
    "json_build_object(any)",
    "jsonb_build_array(any)",
    "jsonb_build_object(any)",
    "num_nonnulls(any)",
    "num_nulls(any)",
];

/// Builtin aggregates that can return NULL for a *non-empty* set of
/// non-NULL inputs. From the same scan, applied to each aggregate's final
/// function: of the NULL-return conditions found, `state == NULL`,
/// `N == 0`, `count == 0` and `PG_ARGISNULL(0)` hold only for an empty (or
/// all-NULL) set, while `N <= 1` / `N < 2` (sample statistics over one
/// row) and `Sxx == 0` / `Syy == 0` (zero variance) hold for real rows.
/// Confirmed on PG 18 with single-row groups.
pub(crate) const NULLABLE_AGGREGATES_OVER_ROWS: &[&str] = &[
    "corr",
    "covar_samp",
    "regr_intercept",
    "regr_r2",
    "regr_slope",
    "stddev",
    "stddev_samp",
    "var_samp",
    "variance",
];
