//! Soundness regressions in what INSERT, UPDATE, DELETE and MERGE return:
//! shapes where the analyzer inferred NOT NULL for a value PostgreSQL 18
//! returns NULL for (or rejected a statement PG runs), each reproduced on
//! PG 18. Every test also pins the near misses that must keep narrowing.

use crate::common::*;

#[track_caller]
fn nullable(db: &PgCatalog, sql: &str) -> Vec<bool> {
    db.analyze(sql)
        .unwrap_or_else(|e| panic!("`{sql}`: {e}"))
        .columns
        .iter()
        .map(|c| c.nullable)
        .collect()
}

#[track_caller]
fn rejected(db: &PgCatalog, sql: &str) -> String {
    match db.analyze(sql) {
        Ok(_) => panic!("`{sql}` was accepted"),
        Err(e) => e.to_string(),
    }
}

fn db(schema: &str) -> PgCatalog {
    let mut db = PgCatalog::new().unwrap();
    db.apply_sql(schema).unwrap();
    db
}

// ── OVERRIDING USER VALUE ────────────────────────────────────────────────────

const IDENTITY: &str = "
    CREATE TABLE idt (id int GENERATED BY DEFAULT AS IDENTITY, a int,
                      CHECK (id > 0 OR a IS NOT NULL));
    CREATE TABLE ida (id int GENERATED ALWAYS AS IDENTITY, a int,
                      CHECK (id > 0 OR a IS NOT NULL));
    CREATE VIEW vidt AS SELECT id, a FROM idt;
    CREATE TABLE src (x int);";

#[test]
fn overriding_user_value_stores_the_sequence_value_not_the_given_one() {
    // The -5 is discarded for the sequence's next value (positive), so the
    // CHECK says nothing of `a`.
    let db = db(IDENTITY);
    for table in ["idt", "ida", "vidt"] {
        assert_eq!(
            nullable(
                &db,
                &format!(
                    "INSERT INTO {table}(id, a) OVERRIDING USER VALUE \
                     VALUES (-5, NULLIF(1, 1)) RETURNING id, a"
                )
            ),
            [false, true],
            "{table}"
        );
    }
    assert_eq!(
        nullable(
            &db,
            "INSERT INTO idt(id, a) OVERRIDING USER VALUE SELECT -5, NULLIF(1, 1) \
             RETURNING id, a"
        ),
        [false, true]
    );
    assert_eq!(
        nullable(
            &db,
            "MERGE INTO idt USING src ON false WHEN NOT MATCHED THEN \
             INSERT (id, a) OVERRIDING USER VALUE VALUES (-5, NULLIF(1, 1)) RETURNING id, a"
        ),
        [false, true]
    );
    // The value given is stored without OVERRIDING (BY DEFAULT) or with
    // OVERRIDING SYSTEM VALUE: -5 fails the CHECK unless `a` is set.
    assert_eq!(
        nullable(
            &db,
            "INSERT INTO idt(id, a) VALUES (-5, NULLIF(1, 1)) RETURNING id, a"
        ),
        [false, false]
    );
    assert_eq!(
        nullable(
            &db,
            "INSERT INTO ida(id, a) OVERRIDING SYSTEM VALUE VALUES (-5, NULLIF(1, 1)) \
             RETURNING id, a"
        ),
        [false, false]
    );
}

#[test]
fn overriding_user_value_accepts_a_null_for_an_identity_column() {
    let db = db(IDENTITY);
    for sql in [
        "INSERT INTO idt(id, a) OVERRIDING USER VALUE VALUES (NULL, 1) RETURNING id",
        "INSERT INTO ida(id, a) OVERRIDING USER VALUE VALUES (NULL, 1) RETURNING id",
        "INSERT INTO vidt(id, a) OVERRIDING USER VALUE VALUES (NULL, 1) RETURNING id",
        "MERGE INTO idt USING src ON false WHEN NOT MATCHED THEN \
         INSERT (id, a) OVERRIDING USER VALUE VALUES (NULL, 1) RETURNING id",
    ] {
        assert_eq!(nullable(&db, sql), [false], "{sql}");
    }
    // A parameter there may be NULL too.
    let a = db
        .analyze("INSERT INTO idt(id, a) OVERRIDING USER VALUE VALUES ($1, 1)")
        .unwrap();
    assert!(a.params[0].nullable);
    let a = db.analyze("INSERT INTO idt(id, a) VALUES ($1, 1)").unwrap();
    assert!(!a.params[0].nullable);
    // Stored as given, the NULL violates the identity column's NOT NULL.
    for sql in [
        "INSERT INTO idt(id, a) VALUES (NULL, 1)",
        "INSERT INTO ida(id, a) OVERRIDING SYSTEM VALUE VALUES (NULL, 1)",
        "INSERT INTO vidt(id, a) VALUES (NULL, 1)",
    ] {
        assert!(
            rejected(&db, sql).starts_with("null value in column \"id\""),
            "{sql}"
        );
    }
}

// ── Data-modifying CTE row counts ───────────────────────────────────────────

#[test]
fn a_set_returning_function_in_a_one_row_values_inserts_any_number_of_rows() {
    let db = db("CREATE TABLE t (id int NOT NULL, a int);");
    let srf = "WITH i AS (INSERT INTO t(id) VALUES (generate_series(1, 0)) RETURNING id)";
    assert_eq!(
        nullable(
            &db,
            &format!("{srf} SELECT x.v, i.id FROM (SELECT 1 AS v) x LEFT JOIN i ON true")
        ),
        [false, true]
    );
    assert_eq!(
        nullable(&db, &format!("{srf} SELECT (SELECT id FROM i) AS s")),
        [true]
    );
    // One plain VALUES row is exactly one row.
    let one = "WITH i AS (INSERT INTO t(id) VALUES (1) RETURNING id)";
    assert_eq!(
        nullable(
            &db,
            &format!("{one} SELECT x.v, i.id FROM (SELECT 1 AS v) x LEFT JOIN i ON true")
        ),
        [false, false]
    );
    assert_eq!(
        nullable(&db, &format!("{one} SELECT (SELECT id FROM i) AS s")),
        [false]
    );
}

// ── Rows written through views ──────────────────────────────────────────────

const VIEW_CHAIN: &str = "
    CREATE TABLE t (id int, a int, b text);
    CREATE VIEW v1 AS SELECT id, a, b FROM t WHERE a IS NOT NULL;
    CREATE VIEW v2 AS SELECT id, a, b FROM v1;
    CREATE VIEW v3 AS SELECT id, a, coalesce(b, 'x') AS cb FROM t WHERE b IS NOT NULL;
    CREATE VIEW v4 AS SELECT * FROM v3 WHERE id > 0;
    CREATE TABLE src (id int, a int);";

#[test]
fn a_row_written_through_a_view_of_a_view_need_not_pass_the_inner_where() {
    let db = db(VIEW_CHAIN);
    assert_eq!(
        nullable(&db, "INSERT INTO v2 VALUES (1, NULL) RETURNING a"),
        [true]
    );
    assert_eq!(
        nullable(&db, "UPDATE v2 SET a = NULL RETURNING a, new.a"),
        [true, true]
    );
    assert_eq!(
        nullable(
            &db,
            "MERGE INTO v2 USING src ON v2.id = src.id \
             WHEN MATCHED THEN UPDATE SET a = src.a \
             WHEN NOT MATCHED THEN INSERT VALUES (src.id, src.a) RETURNING v2.a"
        ),
        [true]
    );
    assert_eq!(
        nullable(
            &db,
            "WITH x AS (UPDATE v2 SET a = NULL RETURNING *) SELECT a FROM x"
        ),
        [true]
    );
    // A row of the view passed both WHEREs; an expression non-NULL over
    // any row stays so in a written one.
    assert_eq!(nullable(&db, "SELECT a FROM v2"), [false]);
    assert_eq!(nullable(&db, "DELETE FROM v2 RETURNING a"), [false]);
    assert_eq!(
        nullable(&db, "INSERT INTO v4(id, a) VALUES (1, NULL) RETURNING cb"),
        [false]
    );
}

#[test]
fn the_foreign_key_of_a_row_written_through_a_view_vouches_for_no_parent() {
    // The parent the CTE inserts is not in the snapshot RETURNING's
    // subquery reads.
    let db = db(
        "CREATE TABLE other (id int PRIMARY KEY, name text NOT NULL);
         CREATE TABLE t (id int, other_id int NOT NULL REFERENCES other);
         CREATE VIEW v AS SELECT id, other_id,
             (SELECT name FROM other o WHERE o.id = t.other_id) AS sx FROM t;",
    );
    assert_eq!(
        nullable(
            &db,
            "WITH p AS (INSERT INTO other VALUES (7, 'n')) \
             INSERT INTO v(id, other_id) VALUES (1, 7) RETURNING sx"
        ),
        [true]
    );
    assert_eq!(
        nullable(&db, "UPDATE v SET other_id = 7 RETURNING sx"),
        [true]
    );
    // A stored row's parent exists.
    assert_eq!(nullable(&db, "SELECT sx FROM v"), [false]);
    assert_eq!(nullable(&db, "DELETE FROM v RETURNING sx"), [false]);
}

#[test]
fn a_view_exposing_a_column_twice_writes_whichever_is_given() {
    let db = db("CREATE TABLE t (id int, a int DEFAULT 5, b int);
         CREATE VIEW v AS SELECT id, a, a AS a2, b FROM t;
         CREATE TABLE t2 (id int, a int, b int);
         CREATE VIEW v2 AS SELECT id, a, a AS a2 FROM t2;
         ALTER VIEW v2 ALTER COLUMN a2 SET DEFAULT 7;");
    for sql in [
        "INSERT INTO v(id, a2) VALUES (1, NULL) RETURNING a, a2",
        "INSERT INTO v(id, a) VALUES (1, NULL) RETURNING a, a2",
    ] {
        assert_eq!(nullable(&db, sql), [true, true], "{sql}");
    }
    // Omitted: the base default, or a view default of either column.
    assert_eq!(
        nullable(&db, "INSERT INTO v(id) VALUES (1) RETURNING a, a2"),
        [false, false]
    );
    assert_eq!(
        nullable(&db, "INSERT INTO v2(id) VALUES (1) RETURNING a, a2"),
        [false, false]
    );
}

#[test]
fn every_view_down_the_chain_supplies_its_defaults() {
    let db = db(
        "CREATE TABLE t (id int, a int, b int, CHECK (a IS NOT NULL OR b IS NOT NULL));
         CREATE VIEW v1 AS SELECT id, a, b FROM t;
         ALTER VIEW v1 ALTER COLUMN a SET DEFAULT 5;
         CREATE VIEW v2 AS SELECT id, b FROM v1;
         CREATE TABLE t3 (id int, a int, b int, CHECK (a IS NOT NULL OR b IS NOT NULL));
         CREATE VIEW w1 AS SELECT id, a, b FROM t3;
         CREATE VIEW w2 AS SELECT id, b FROM w1;",
    );
    // v1's default fills `a` for a row inserted through v2.
    assert_eq!(
        nullable(&db, "INSERT INTO v2 VALUES (1, NULLIF(1, 1)) RETURNING b"),
        [true]
    );
    assert_eq!(
        nullable(
            &db,
            "INSERT INTO v1(id, b) VALUES (1, NULLIF(1, 1)) RETURNING b"
        ),
        [true]
    );
    // No default anywhere: `a` is NULL, so the CHECK needs `b`.
    for sql in [
        "INSERT INTO t(id, b) VALUES (1, NULLIF(1, 1)) RETURNING b",
        "INSERT INTO w1(id, b) VALUES (1, NULLIF(1, 1)) RETURNING b",
        "INSERT INTO w2(id, b) VALUES (1, NULLIF(1, 1)) RETURNING b",
    ] {
        assert_eq!(nullable(&db, sql), [false], "{sql}");
    }
}

#[test]
fn a_domain_typed_view_column_takes_the_domain_default() {
    // The view's own level fills the omitted column with its type's
    // default (5), not the base column's `DEFAULT NULL`.
    let db = db("CREATE DOMAIN d AS int DEFAULT 5;
         CREATE TABLE dd (id int, y d DEFAULT NULL, a int,
                          CHECK (y IS NOT NULL OR a IS NOT NULL));
         CREATE VIEW vdd AS SELECT id, y, a FROM dd;");
    assert_eq!(
        nullable(
            &db,
            "INSERT INTO vdd(id, a) VALUES (2, NULLIF(1, 1)) RETURNING y, a"
        ),
        [true, true]
    );
    assert_eq!(
        nullable(
            &db,
            "INSERT INTO dd(id, a) VALUES (2, NULLIF(1, 1)) RETURNING y, a"
        ),
        [true, false]
    );
}

#[test]
fn update_set_default_through_a_view_uses_the_view_default_only() {
    // rewriteTargetListIU sets a view column without a default of its own
    // to NULL; it doesn't reach for the base column's.
    let db = db("CREATE TABLE t (id int, a int DEFAULT 5);
         CREATE VIEW v AS SELECT id, a FROM t;
         CREATE VIEW vd AS SELECT id, a FROM t;
         ALTER VIEW vd ALTER COLUMN a SET DEFAULT 7;");
    assert_eq!(
        nullable(&db, "UPDATE v SET a = DEFAULT RETURNING a"),
        [true]
    );
    assert_eq!(
        nullable(&db, "UPDATE vd SET a = DEFAULT RETURNING a"),
        [false]
    );
    assert_eq!(
        nullable(&db, "UPDATE t SET a = DEFAULT RETURNING a"),
        [false]
    );
}

// ── DO INSTEAD rules ─────────────────────────────────────────────────────────

#[test]
fn a_do_instead_rule_returns_its_own_rows() {
    let db = db("CREATE TABLE tbl (id int NOT NULL, a int NOT NULL);
         CREATE TABLE other (id int, a int);
         CREATE RULE r_ins AS ON INSERT TO tbl DO INSTEAD
             INSERT INTO other VALUES (NEW.id, NULL) RETURNING other.id, other.a;
         CREATE RULE r_upd AS ON UPDATE TO tbl DO INSTEAD
             UPDATE other SET a = NULL WHERE other.id = OLD.id RETURNING other.id, other.a;
         CREATE RULE r_del AS ON DELETE TO tbl DO INSTEAD
             DELETE FROM other WHERE other.id = OLD.id RETURNING other.id, other.a;
         CREATE VIEW vv AS SELECT id, a FROM tbl;
         CREATE TABLE plain (id int NOT NULL, a int NOT NULL);
         CREATE TABLE log (id int);
         CREATE RULE r_log AS ON INSERT TO plain DO ALSO INSERT INTO log VALUES (NEW.id);
         CREATE RULE r_pdel AS ON DELETE TO plain DO INSTEAD
             DELETE FROM other WHERE other.id = OLD.id RETURNING other.id, other.a;");
    for sql in [
        "INSERT INTO tbl VALUES (1, 2) RETURNING id, a",
        "UPDATE tbl SET a = 5 RETURNING id, a",
        "DELETE FROM tbl RETURNING id, a",
        "INSERT INTO vv VALUES (1, 2) RETURNING id, a",
        "UPDATE vv SET a = 5 RETURNING id, a",
        "DELETE FROM vv RETURNING id, a",
        "WITH x AS (INSERT INTO tbl VALUES (1, 2) RETURNING id, a) SELECT id, a FROM x",
        "DELETE FROM plain RETURNING id, a",
    ] {
        assert_eq!(nullable(&db, sql), [true, true], "{sql}");
    }
    // The whole row's fields too.
    let a = db
        .analyze("INSERT INTO tbl VALUES (1, 2) RETURNING tbl")
        .unwrap();
    let Type::Composite { fields, .. } = &a.columns[0].pg_type else {
        panic!("{:?}", a.columns[0].pg_type);
    };
    assert!(fields.iter().all(|f| f.nullable));
    // An ALSO rule leaves the statement's own RETURNING, and a rule for
    // another event changes nothing.
    assert_eq!(
        nullable(&db, "INSERT INTO plain VALUES (1, 2) RETURNING id, a"),
        [false, false]
    );
    assert_eq!(
        nullable(&db, "UPDATE plain SET a = 3 RETURNING id, a"),
        [false, false]
    );
}

#[test]
fn a_do_instead_rule_under_a_narrowing_view_returns_its_own_rows() {
    let db = db("CREATE TABLE tbl (id int NOT NULL, a int);
         CREATE TABLE other (id int, a int);
         CREATE VIEW v AS SELECT id, a FROM tbl WHERE a IS NOT NULL;
         CREATE VIEW w AS SELECT id, a FROM tbl WHERE a IS NOT NULL;
         CREATE RULE w_del AS ON DELETE TO w DO INSTEAD
             DELETE FROM other WHERE other.id = OLD.id RETURNING other.id, other.a;");
    assert_eq!(nullable(&db, "DELETE FROM w RETURNING a"), [true]);
    // Without one, the deleted rows are the view's.
    assert_eq!(nullable(&db, "DELETE FROM v RETURNING a"), [false]);
}

// ── Assignment coercions ─────────────────────────────────────────────────────

#[test]
fn an_assignment_cast_that_can_return_null_makes_the_stored_value_nullable() {
    // `time(timestamp)` is NULL for infinity; the user's cast function
    // returns NULL outright.
    let db = db("CREATE TYPE pt AS (x int);
         CREATE FUNCTION int_to_pt(int) RETURNS pt LANGUAGE sql AS 'SELECT NULL::pt';
         CREATE CAST (int AS pt) WITH FUNCTION int_to_pt(int) AS ASSIGNMENT;
         CREATE TABLE tc (id int, p pt);
         CREATE TABLE dp (id int, p pt DEFAULT 5);
         CREATE TABLE g (a int NOT NULL, gp pt GENERATED ALWAYS AS (a) STORED,
                         ga bigint GENERATED ALWAYS AS (a) STORED);
         CREATE TABLE tg (id int PRIMARY KEY, ts timestamp NOT NULL,
                          tm time GENERATED ALWAYS AS (ts) STORED,
                          tv time GENERATED ALWAYS AS (ts) VIRTUAL);
         CREATE TABLE td (id int, tm time DEFAULT 'infinity'::timestamp,
                          ts timestamp NOT NULL DEFAULT now(), n bigint);
         CREATE TABLE src (id int);");
    for sql in [
        "INSERT INTO tc VALUES (1, 5) RETURNING p",
        "UPDATE tc SET p = 5 RETURNING p",
        "INSERT INTO tc SELECT 1, 5 RETURNING p",
        "MERGE INTO tc USING src ON false WHEN NOT MATCHED THEN INSERT VALUES (1, 5) RETURNING p",
        "INSERT INTO dp(id) VALUES (1) RETURNING p",
        "SELECT gp FROM g",
        "INSERT INTO g(a) VALUES (2) RETURNING gp",
        "SELECT tm FROM tg",
        "SELECT tv FROM tg",
        "INSERT INTO td(id) VALUES (1) RETURNING tm",
        "UPDATE td SET tm = ts RETURNING tm",
        "INSERT INTO td(id, tm) SELECT 1, ts FROM td RETURNING tm",
    ] {
        assert_eq!(nullable(&db, sql), [true], "{sql}");
    }
    // A cast that can't return NULL, or none at all.
    for sql in [
        "SELECT ga FROM g",
        "INSERT INTO td(id, tm, n) VALUES (1, '10:00', 1) RETURNING tm, n",
        "UPDATE td SET n = id + 1 WHERE id IS NOT NULL RETURNING n",
    ] {
        assert!(nullable(&db, sql).iter().all(|n| !n), "{sql}");
    }
}

// ── Typmod coercions of constants ────────────────────────────────────────────

#[test]
fn a_constant_a_typmod_coercion_changes_is_not_the_stored_value() {
    // numeric(2,-1) rounds 15 to 20, varchar(2) drops 'ab ''s trailing
    // space, timestamp(0) the fractional second: the stored value isn't
    // the one the CHECK excludes.
    let db = db(
        "CREATE TABLE n (x numeric(2,-1), a int, CHECK (x <> 15 OR a IS NOT NULL));
         CREATE TABLE nd (x numeric(2,-1) DEFAULT 15, a int, CHECK (x <> 15 OR a IS NOT NULL));
         CREATE TABLE vc (c varchar(2), a int, CHECK (c <> 'ab ' OR a IS NOT NULL));
         CREATE TABLE ts (t timestamp(0), a int,
                          CHECK (t <> '2020-01-01 00:00:00.4' OR a IS NOT NULL));
         CREATE TABLE n1 (x numeric(4,1), a int, CHECK (x <> 15 OR a IS NOT NULL));
         CREATE TABLE vc5 (c varchar(5), a int, CHECK (c <> 'ab' OR a IS NOT NULL));
         CREATE TABLE src (id int);",
    );
    for sql in [
        "INSERT INTO n VALUES (15, NULLIF(1, 1)) RETURNING a",
        "INSERT INTO nd(a) VALUES (NULLIF(1, 1)) RETURNING a",
        "INSERT INTO vc VALUES ('ab ', NULLIF(1, 1)) RETURNING a",
        "UPDATE vc SET c = 'ab ' RETURNING a",
        "MERGE INTO vc USING src ON false WHEN NOT MATCHED THEN \
         INSERT VALUES ('ab ', NULLIF(1, 1)) RETURNING a",
        "INSERT INTO ts VALUES ('2020-01-01 00:00:00.4', NULLIF(1, 1)) RETURNING a",
    ] {
        assert_eq!(nullable(&db, sql), [true], "{sql}");
    }
    // A constant the typmod keeps as written.
    for sql in [
        "INSERT INTO n1 VALUES (15, NULLIF(1, 1)) RETURNING a",
        "INSERT INTO vc5 VALUES ('ab', NULLIF(1, 1)) RETURNING a",
        "UPDATE vc5 SET c = 'ab' RETURNING a",
    ] {
        assert_eq!(nullable(&db, sql), [false], "{sql}");
    }
}

// ── BEFORE ROW triggers and the literal-NULL rejection ───────────────────────

const FILL: &str = "
    CREATE FUNCTION fill() RETURNS trigger LANGUAGE plpgsql
        AS $$ BEGIN NEW.a := coalesce(NEW.a, 0); RETURN NEW; END $$;";

#[test]
fn a_before_row_trigger_may_fill_a_null_written_to_a_not_null_column() {
    // ExecConstraints checks NOT NULL after the BEFORE ROW triggers.
    let db = db(&format!(
        "{FILL}
         CREATE TABLE t (id int, a int NOT NULL);
         CREATE TRIGGER tr BEFORE INSERT OR UPDATE ON t
             FOR EACH ROW EXECUTE FUNCTION fill();
         CREATE TABLE pt (k int, a int NOT NULL) PARTITION BY LIST (k);
         CREATE TABLE pt1 PARTITION OF pt FOR VALUES IN (1);
         CREATE TABLE pt2 PARTITION OF pt FOR VALUES IN (2);
         CREATE TRIGGER tr BEFORE INSERT ON pt2 FOR EACH ROW EXECUTE FUNCTION fill();
         CREATE TABLE src (id int);"
    ));
    for sql in [
        "INSERT INTO t VALUES (2, NULL) RETURNING a",
        "UPDATE t SET a = NULL RETURNING a",
        "MERGE INTO t USING src ON t.id = src.id \
         WHEN MATCHED THEN UPDATE SET a = NULL \
         WHEN NOT MATCHED THEN INSERT VALUES (src.id, NULL) RETURNING a",
        // Routed to a partition with such a trigger, or moved into it.
        "INSERT INTO pt VALUES (2, NULL) RETURNING a",
        "UPDATE pt SET k = 2, a = NULL RETURNING a",
    ] {
        assert_eq!(nullable(&db, sql), [false], "{sql}");
    }
}

#[test]
fn only_a_before_row_trigger_for_the_event_may_fill_a_null() {
    let db = db(&format!(
        "{FILL}
         CREATE TABLE ta (id int, a int NOT NULL);
         CREATE TRIGGER tr AFTER INSERT OR UPDATE ON ta FOR EACH ROW EXECUTE FUNCTION fill();
         CREATE TABLE tdel (id int, a int NOT NULL);
         CREATE TRIGGER tr BEFORE DELETE ON tdel FOR EACH ROW EXECUTE FUNCTION fill();
         CREATE DOMAIN nn AS int NOT NULL;
         CREATE TABLE tdom (id int, a nn);
         CREATE TRIGGER tr BEFORE INSERT ON tdom FOR EACH ROW EXECUTE FUNCTION fill();
         CREATE TABLE pt (k int, a int NOT NULL) PARTITION BY LIST (k);
         CREATE TABLE pt1 PARTITION OF pt FOR VALUES IN (1);
         CREATE TABLE pt2 PARTITION OF pt FOR VALUES IN (2);
         CREATE TRIGGER tr BEFORE INSERT ON pt2 FOR EACH ROW EXECUTE FUNCTION fill();"
    ));
    // An AFTER trigger, one for another event, or a partition without
    // one: the NOT NULL fails every execution.
    for (sql, column) in [
        ("INSERT INTO ta VALUES (1, NULL)", "a\" of relation \"ta"),
        (
            "INSERT INTO tdel VALUES (1, NULL)",
            "a\" of relation \"tdel",
        ),
        ("INSERT INTO pt1 VALUES (1, NULL)", "a\" of relation \"pt1"),
    ] {
        let err = rejected(&db, sql);
        assert!(
            err.starts_with(&format!("null value in column \"{column}\"")),
            "{sql}: {err}"
        );
    }
    // A NOT NULL domain fails as the row is built, before any trigger.
    assert!(
        rejected(&db, "INSERT INTO tdom VALUES (1, NULL)")
            .starts_with("domain nn does not allow null values")
    );
}
