// @generated by typedpg from the queries in this project's sources. Do not edit:
// run `typedpg gen` after changing a query or a migration.
/* eslint-disable */
import { createCopyIn, createSql } from "@cubos/typedpg";
import type * as typedpg from "@cubos/typedpg";

export interface Queries {
  "SELECT $r::record AS r": { error: "anonymous record-typed query parameters are not supported — pass the fields individually using a ROW(...) constructor in SQL" };
  "SELECT id FROM things WHERE span @> $n": {
    params: {
      n: typedpg.Range<number>;
    };
    row: {
      id: number;
    };
    value: number;
  };
  "SELECT id FROM users WHERE id = $1": { error: "positional placeholder `$1` is not supported in sql(): name the parameter (e.g. `$id`) so it can be bound" };
  "SELECT id FROM users WHERE id = $id": {
    params: {
      id: number;
    };
    row: {
      id: number;
    };
    value: number;
  };
  "SELECT id FROM users WHERE mood = $mood": {
    params: {
      mood: "happy" | "sad" | "neutral";
    };
    row: {
      id: number;
    };
    value: number;
  };
  "SELECT id, name FROM users": {
    params: {};
    row: {
      id: number;
      name: string;
    };
  };
  "SELECT id, nmae FROM users": { error: "column \"nmae\" does not exist" };
  "SELECT now() - $d AS t": {
    params: {
      d: Date | string;
    };
    row: {
      t: typedpg.Interval;
    };
    value: typedpg.Interval;
  };
  "SELECT u.id, p.id FROM users u JOIN posts p ON p.author_id = u.id": { error: "duplicate column name \"id\" in the query's output: a row object has one property per name, so give the columns distinct names (`AS ...`)" };
}

export interface CopyTargets {
  "users (id, nope)": { error: "column \"nope\" of relation \"users\" does not exist" };
  "users (name, email)": {
    row: {
      name: string;
      email: string | null;
    };
  };
}

export const sql = createSql<Queries>({
  "SELECT id FROM things WHERE span @> $n": "{\"sql\":[\"SELECT id FROM things WHERE span @> ($1::pg_catalog.int4range)\"],\"params\":[[\"n\",[\"range\",\"number\"]]],\"columns\":[[\"id\",\"number\"]],\"subquery\":true}",
  "SELECT id FROM users WHERE id = $id": "{\"sql\":[\"SELECT id FROM users WHERE id = ($1::pg_catalog.int4)\"],\"params\":[[\"id\",\"number\"]],\"columns\":[[\"id\",\"number\"]],\"subquery\":true}",
  "SELECT id FROM users WHERE mood = $mood": "{\"sql\":[\"SELECT id FROM users WHERE mood = ($1::public.mood)\"],\"params\":[[\"mood\",\"text\"]],\"columns\":[[\"id\",\"number\"]],\"subquery\":true}",
  "SELECT id, name FROM users": "{\"sql\":[\"SELECT id, name FROM users\"],\"params\":[],\"columns\":[[\"id\",\"number\"],[\"name\",\"text\"]],\"subquery\":true}",
  "SELECT now() - $d AS t": "{\"sql\":[\"SELECT now() - ($1::pg_catalog.timestamptz) AS t\"],\"params\":[[\"d\",\"timestamptz\"]],\"columns\":[[\"t\",\"interval\"]],\"subquery\":true}",
});
export const copyIn = createCopyIn<CopyTargets>({
  "users (name, email)": "{\"sql\":\"COPY public.users (name, email) FROM STDIN\",\"columns\":[[\"name\",\"text\"],[\"email\",\"text\"]]}",
});
