// @generated by typedpg from the queries in this project's sources. Do not edit:
// run `typedpg gen` after changing a query or a migration.
/* eslint-disable */
import { createCopyIn, createSql } from "@cubos/typedpg";
import type * as typedpg from "@cubos/typedpg";
import type { Address, Embedding, EmbeddingText, Instant, JsonPath, Mood, Prefs, ShortAddress, UserId } from "./types.ts";

// Each type in `types` must fit what its PostgreSQL type is read as.
export type TypeMappingChecks = [
  typedpg.Fits<Instant, Date>, // pg_catalog.timestamptz
  typedpg.Fits<Address, { readonly street: string | null; readonly number: number | null }>, // public.address
  typedpg.Fits<Embedding, readonly number[]>, // public.embedding
  typedpg.Fits<EmbeddingText, readonly number[]>, // public.embedding_text
  typedpg.Fits<Mood, string>, // public.mood
  typedpg.Fits<Prefs, unknown>, // public.prefs
  typedpg.Fits<ShortAddress, { readonly street: string | null; readonly number: number | null }>, // public.short_address
  typedpg.Fits<UserId, bigint>, // public.user_id
];

export interface Queries {
}

export interface CopyTargets {
}

export const sql = createSql<Queries>({
});
export const copyIn = createCopyIn<CopyTargets>({
});
