//! The generated module of a database.
//!
//! ```ts
//! import { createCopyIn, createSql } from "@cubos/typedpg";
//!
//! export interface Queries {
//!   "SELECT name FROM users WHERE id = $id": {
//!     params: { id: number };
//!     row: { name: string | null };
//!     value: string | null;
//!   };
//!   "SELECT nmae FROM users": { error: "column \"nmae\" does not exist" };
//! }
//!
//! export interface CopyTargets {
//!   "users (name, email)": { row: { name: string; email: string | null } };
//! }
//!
//! export const sql = createSql<Queries>({
//!   "SELECT name FROM users WHERE id = $id": "{\"sql\":[...],\"params\":[...],...}",
//! });
//! export const copyIn = createCopyIn<CopyTargets>({ ... });
//! ```
//!
//! A `.js` / `.mjs` / `.cjs` `out` is the same split in two: the values in
//! the JavaScript module, the interfaces in its declaration file. Entries are
//! sorted by text, so the output is deterministic and a new query is a local
//! diff.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use typedpg_core::config::MigrationsConfig;

use crate::config::{OutKind, declaration_path};
use crate::generate::{GenError, Generated};
use crate::typemap::{RUNTIME_NS, js_string};

/// A query's or COPY target's text and what was generated for it.
pub type Entry<'a> = (&'a str, &'a Result<Generated, GenError>);

/// The migrations a module embeds, and the runner's settings.
pub struct Embedded<'a> {
    /// `(name, up SQL, down SQL)`.
    pub migrations: &'a [(String, String, Option<String>)],
    pub runner: &'a MigrationsConfig,
}

pub struct Module<'a> {
    pub runtime: &'a str,
    /// `(module, type name)` the type mappings need.
    pub imports: &'a [(String, String)],
    pub queries: &'a [Entry<'a>],
    pub copies: &'a [Entry<'a>],
    pub migrations: Option<Embedded<'a>>,
}

const HEADER: &str = "// @generated by typedpg from the queries in this project's sources. Do \
                      not edit:\n// run `typedpg gen` after changing a query or a \
                      migration.\n/* eslint-disable */\n";

impl Module<'_> {
    /// The files of the module at `out`: `(path, contents)`.
    pub fn files(&self, out: &Path, kind: OutKind) -> Vec<(PathBuf, String)> {
        match kind {
            OutKind::TypeScript => vec![(out.to_path_buf(), self.typescript())],
            OutKind::EsModule | OutKind::CommonJs => {
                let declaration = declaration_path(out).expect("a JavaScript out");
                vec![
                    (
                        out.to_path_buf(),
                        self.javascript(kind == OutKind::CommonJs),
                    ),
                    (declaration, self.declaration()),
                ]
            }
        }
    }

    fn typescript(&self) -> String {
        let mut out = String::from(HEADER);
        let mut values = vec!["createCopyIn", "createSql"];
        if self.migrations.is_some() {
            values.push("embedMigrations");
        }
        let runtime = js_string(self.runtime);
        let _ = writeln!(out, "import {{ {} }} from {runtime};", values.join(", "));
        self.type_imports(&mut out);
        out.push('\n');
        self.interfaces(&mut out);
        out.push('\n');
        self.values(&mut out, "export const ", "<Queries>", "<CopyTargets>");
        out
    }

    fn javascript(&self, commonjs: bool) -> String {
        let mut out = String::from(HEADER);
        let mut values = vec!["createCopyIn", "createSql"];
        if self.migrations.is_some() {
            values.push("embedMigrations");
        }
        let runtime = js_string(self.runtime);
        if commonjs {
            let _ = writeln!(
                out,
                "\"use strict\";\nconst {{ {} }} = require({runtime});\n",
                values.join(", ")
            );
            self.values(&mut out, "exports.", "", "");
        } else {
            let _ = writeln!(out, "import {{ {} }} from {runtime};\n", values.join(", "));
            self.values(&mut out, "export const ", "", "");
        }
        out
    }

    fn declaration(&self) -> String {
        let mut out = String::from(HEADER);
        let _ = writeln!(
            out,
            "import type * as {RUNTIME_NS} from {};",
            js_string(self.runtime)
        );
        self.user_imports(&mut out);
        out.push('\n');
        self.interfaces(&mut out);
        let _ = writeln!(
            out,
            "\nexport declare const sql: {RUNTIME_NS}.Sql<Queries>;\n\
             export declare const copyIn: {RUNTIME_NS}.CopyIn<CopyTargets>;"
        );
        if self.migrations.is_some() {
            let _ = writeln!(
                out,
                "export declare const migrations: {RUNTIME_NS}.MigrationSet;"
            );
        }
        out
    }

    fn uses_runtime_types(&self) -> bool {
        let prefix = format!("{RUNTIME_NS}.");
        self.queries
            .iter()
            .chain(self.copies)
            .any(|(_, r)| r.as_ref().is_ok_and(|g| g.types.contains(&prefix)))
    }

    fn type_imports(&self, out: &mut String) {
        if self.uses_runtime_types() {
            let _ = writeln!(
                out,
                "import type * as {RUNTIME_NS} from {};",
                js_string(self.runtime)
            );
        }
        self.user_imports(out);
    }

    /// One `import type` per module, the names sorted (`imports` is).
    fn user_imports(&self, out: &mut String) {
        let mut i = 0;
        while i < self.imports.len() {
            let module = &self.imports[i].0;
            let names: Vec<&str> = self.imports[i..]
                .iter()
                .take_while(|(m, _)| m == module)
                .map(|(_, n)| n.as_str())
                .collect();
            i += names.len();
            let _ = writeln!(
                out,
                "import type {{ {} }} from {};",
                names.join(", "),
                js_string(module)
            );
        }
    }

    fn interfaces(&self, out: &mut String) {
        for (name, entries) in [("Queries", self.queries), ("CopyTargets", self.copies)] {
            if name == "CopyTargets" {
                out.push('\n');
            }
            let _ = writeln!(out, "export interface {name} {{");
            for (text, result) in entries {
                let key = js_string(text);
                match result {
                    Ok(g) => {
                        let _ = writeln!(out, "  {key}: {};", g.types);
                    }
                    Err(e) => {
                        // The message's first line: the rest is the
                        // rendered snippet, which the CLI prints.
                        let first = e.message.lines().next().unwrap_or_default();
                        let _ = writeln!(out, "  {key}: {{ error: {} }};", js_string(first));
                    }
                }
            }
            out.push_str("}\n");
        }
    }

    fn values(&self, out: &mut String, export: &str, queries_ty: &str, copies_ty: &str) {
        for (name, create, ty, entries) in [
            ("sql", "createSql", queries_ty, self.queries),
            ("copyIn", "createCopyIn", copies_ty, self.copies),
        ] {
            let _ = writeln!(out, "{export}{name} = {create}{ty}({{");
            for (text, result) in entries {
                if let Ok(g) = result {
                    let _ = writeln!(out, "  {}: {},", js_string(text), js_string(&g.runtime));
                }
            }
            out.push_str("});\n");
        }
        if let Some(m) = &self.migrations {
            let _ = writeln!(out, "{export}migrations = embedMigrations([");
            for (name, sql, down) in m.migrations {
                let down = down.as_deref().map_or_else(|| "null".to_owned(), js_string);
                let _ = writeln!(out, "  [{}, {}, {down}],", js_string(name), js_string(sql));
            }
            let r = m.runner;
            let _ = writeln!(
                out,
                "], {{ table: {}, lockId: {}, useTransaction: {}, failOnDrift: {} }});",
                js_string(&r.table),
                r.lock_id,
                r.use_transaction,
                r.fail_on_drift
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generated(types: &str) -> Result<Generated, GenError> {
        Ok(Generated {
            types: types.to_owned(),
            runtime: "{\"sql\":[\"x\"]}".to_owned(),
        })
    }

    #[test]
    fn typescript_module() {
        let q = generated("{ params: {}; row: { r: typedpg.Range<number> } }");
        let e = Err(GenError {
            message: "column \"x\" does not exist\n  ╭────".into(),
            offset: Some(7),
        });
        let queries = [("SELECT r", &q), ("SELECT x", &e)];
        let imports = [
            ("./domains".to_owned(), "Point".to_owned()),
            ("./domains".to_owned(), "Prefs".to_owned()),
            ("pkg".to_owned(), "X".to_owned()),
        ];
        let m = Module {
            runtime: "@cubos/typedpg",
            imports: &imports,
            queries: &queries,
            copies: &[],
            migrations: None,
        };
        let files = m.files(Path::new("/p/db.ts"), OutKind::TypeScript);
        assert_eq!(files.len(), 1);
        let ts = &files[0].1;
        assert!(ts.contains("import { createCopyIn, createSql } from \"@cubos/typedpg\";\nimport type * as typedpg from \"@cubos/typedpg\";\nimport type { Point, Prefs } from \"./domains\";\nimport type { X } from \"pkg\";"), "{ts}");
        assert!(
            ts.contains(r#"  "SELECT x": { error: "column \"x\" does not exist" };"#),
            "{ts}"
        );
        assert!(ts.contains("export const sql = createSql<Queries>({\n  \"SELECT r\": \"{\\\"sql\\\":[\\\"x\\\"]}\",\n});"), "{ts}");
        assert!(ts.contains("export interface CopyTargets {\n}"), "{ts}");
        assert!(
            ts.contains("export const copyIn = createCopyIn<CopyTargets>({\n});"),
            "{ts}"
        );
    }

    #[test]
    fn javascript_modules_come_with_declarations() {
        let q = generated("{ params: {}; row: {} }");
        let queries = [("SELECT", &q)];
        let runner = MigrationsConfig::default();
        let migrations = [("0001_a".to_owned(), "CREATE TABLE a ();".to_owned(), None)];
        let m = Module {
            runtime: "@cubos/typedpg",
            imports: &[],
            queries: &queries,
            copies: &[],
            migrations: Some(Embedded {
                migrations: &migrations,
                runner: &runner,
            }),
        };
        let files = m.files(Path::new("/p/db.cjs"), OutKind::CommonJs);
        assert_eq!(files[0].0, PathBuf::from("/p/db.cjs"));
        assert_eq!(files[1].0, PathBuf::from("/p/db.d.cts"));
        let (js, dts) = (&files[0].1, &files[1].1);
        assert!(
            js.contains(
                "const { createCopyIn, createSql, embedMigrations } = require(\"@cubos/typedpg\");"
            ),
            "{js}"
        );
        assert!(js.contains("exports.sql = createSql({"), "{js}");
        assert!(js.contains("exports.migrations = embedMigrations([\n  [\"0001_a\", \"CREATE TABLE a ();\", null],\n], { table: \"public._migrations\", lockId: 713705, useTransaction: true, failOnDrift: true });"), "{js}");
        assert!(!js.contains("interface"), "{js}");
        assert!(
            dts.contains("export declare const sql: typedpg.Sql<Queries>;"),
            "{dts}"
        );
        assert!(
            dts.contains("export declare const migrations: typedpg.MigrationSet;"),
            "{dts}"
        );

        let files = m.files(Path::new("/p/db.js"), OutKind::EsModule);
        assert_eq!(files[1].0, PathBuf::from("/p/db.d.ts"));
        assert!(files[0].1.contains("export const sql = createSql({"));
    }
}
