//! Code generation for `typedpg_pg_query`.
//!
//! Everything version-specific in the binding is derived from libpg_query's
//! `pg_query.proto`, so moving the submodule to a new PostgreSQL release only
//! needs a rerun:
//!
//! - `src/protobuf.rs`: the AST message types, generated by `prost-build`
//!   (the `.proto` is compiled by `protox`, so no `protoc` is needed);
//! - `src/node.rs`: the `NodeRef` / `NodeMut` views over the `Node` oneof and
//!   the per-message child walkers behind `nodes()` / `nodes_mut()`;
//! - `src/equal.rs`: PostgreSQL's `equal()` over the messages — every field
//!   compared except the ones `equalfuncs.c` skips (parse locations and
//!   `equal_ignore` fields), read from the PostgreSQL headers libpg_query
//!   vendors — and the matching key, a string over the same fields.
//!
//! A child walker visits every field of a message: a `Node` field yields the
//! node it wraps, a field whose message type is itself a `Node` variant
//! yields that message, and any other message field (or oneof) is descended
//! into without yielding.

use std::collections::{HashMap, HashSet};
use std::fmt::Write;
use std::path::{Path, PathBuf};

use heck::{ToSnakeCase, ToUpperCamelCase};
use prost_types::field_descriptor_proto::{Label, Type};
use prost_types::{DescriptorProto, FieldDescriptorProto, FileDescriptorSet};

/// The `typedpg_pg_query` crate directory, next to this one.
pub fn crate_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../typedpg_pg_query")
}

/// The generated files of the crate at `crate_dir`, as `(path, content)`.
pub fn generate(crate_dir: &Path) -> Vec<(PathBuf, String)> {
    let proto_dir = crate_dir.join("libpg_query/protobuf");
    let fds = protox::compile(["pg_query.proto"], [&proto_dir])
        .unwrap_or_else(|e| panic!("compiling {}/pg_query.proto: {e}", proto_dir.display()));
    let ignored = equal_ignored(&crate_dir.join("libpg_query/src/postgres/include/nodes"));
    vec![
        (
            crate_dir.join("src/protobuf.rs"),
            rustfmt(&message_types(&fds)),
        ),
        (crate_dir.join("src/node.rs"), rustfmt(&walkers(&fds))),
        (
            crate_dir.join("src/equal.rs"),
            rustfmt(&equality(&fds, &ignored)),
        ),
    ]
}

const HEADER: &str = "// @generated by typedpg_pg_query_codegen from libpg_query's pg_query.proto.\n\
                      // Do not edit; run `cargo run -p typedpg_pg_query_codegen`.\n\n";

/// `prost-build`'s output for the `.proto`.
fn message_types(fds: &FileDescriptorSet) -> String {
    let out = std::env::temp_dir().join(format!("typedpg_pg_query_codegen_{}", std::process::id()));
    std::fs::create_dir_all(&out).expect("creating a temporary output directory");
    prost_build::Config::new()
        .out_dir(&out)
        .compile_fds(fds.clone())
        .expect("generating the protobuf types");
    let generated = std::fs::read_to_string(out.join("pg_query.rs")).expect("reading prost output");
    let _ = std::fs::remove_dir_all(&out);
    format!("{HEADER}{generated}")
}

/// Pipe `code` through `rustfmt`, so the output doesn't depend on how it was
/// assembled.
fn rustfmt(code: &str) -> String {
    use std::io::Write as _;
    let mut child = std::process::Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout", "--quiet"])
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .spawn()
        .expect("running rustfmt");
    child
        .stdin
        .take()
        .expect("rustfmt stdin")
        .write_all(code.as_bytes())
        .expect("writing to rustfmt");
    let output = child.wait_with_output().expect("waiting for rustfmt");
    assert!(
        output.status.success(),
        "rustfmt failed on the generated code"
    );
    String::from_utf8(output.stdout).expect("rustfmt output is UTF-8")
}

/// The Rust name `prost-build` gives a message (`A_Const` → `AConst`).
fn type_ident(proto_type_name: &str) -> String {
    proto_type_name
        .trim_start_matches(".pg_query.")
        .to_upper_camel_case()
}

/// The Rust name `prost-build` gives a field (keywords become raw
/// identifiers, as in `prost_build::ident::to_snake`).
fn field_ident(name: &str) -> String {
    let snake = name.to_snake_case();
    match snake.as_str() {
        "self" | "super" | "extern" | "crate" => format!("{snake}_"),
        "as" | "break" | "const" | "continue" | "else" | "enum" | "false" | "fn" | "for" | "if"
        | "impl" | "in" | "let" | "loop" | "match" | "mod" | "move" | "mut" | "pub" | "ref"
        | "return" | "static" | "struct" | "trait" | "true" | "type" | "unsafe" | "use"
        | "where" | "while" | "dyn" | "abstract" | "become" | "box" | "do" | "final" | "macro"
        | "override" | "priv" | "typeof" | "unsized" | "virtual" | "yield" | "async" | "await"
        | "try" | "gen" => format!("r#{snake}"),
        _ => snake,
    }
}

/// One way a message is reached from a field.
enum Target<'a> {
    /// A `Node`: yield what it wraps.
    Node,
    /// A message that is a `Node` variant: yield it as that variant.
    Variant(&'a str, String),
    /// Any other message: walk it without yielding.
    Plain(String),
}

struct Model<'a> {
    messages: Vec<&'a DescriptorProto>,
    /// `Node` variant → Rust message type.
    variants: Vec<(String, String)>,
    /// Rust message type → its `Node` variant.
    variant_of: HashMap<String, String>,
}

impl<'a> Model<'a> {
    fn new(fds: &'a FileDescriptorSet) -> Self {
        let file = fds
            .file
            .iter()
            .find(|f| f.name() == "pg_query.proto")
            .expect("pg_query.proto in the descriptor set");
        let messages: Vec<&DescriptorProto> = file.message_type.iter().collect();
        // Nested messages (the summary API's) must be plain records: no AST
        // node can sit below them, so the walkers skip fields of their type.
        for m in &messages {
            for nested in &m.nested_type {
                assert!(
                    nested.field.iter().all(|f| f.r#type() != Type::Message)
                        && nested.nested_type.is_empty(),
                    "nested message {}.{} holds messages; the walker generator doesn't \
                     handle that",
                    m.name(),
                    nested.name()
                );
            }
        }
        let node = messages
            .iter()
            .find(|m| m.name() == "Node")
            .expect("message Node");
        let variants: Vec<(String, String)> = node
            .field
            .iter()
            .map(|f| (f.name().to_upper_camel_case(), type_ident(f.type_name())))
            .collect();
        let mut variant_of = HashMap::new();
        for (variant, ty) in &variants {
            assert!(
                variant_of.insert(ty.clone(), variant.clone()).is_none(),
                "message {ty} appears twice in the Node oneof"
            );
        }
        Model {
            messages,
            variants,
            variant_of,
        }
    }

    fn target(&self, field: &FieldDescriptorProto) -> Option<Target<'_>> {
        if field.r#type() != Type::Message {
            return None;
        }
        // A nested (summary) record: `.pg_query.Outer.Inner`.
        if field
            .type_name()
            .trim_start_matches(".pg_query.")
            .contains('.')
        {
            return None;
        }
        let ty = type_ident(field.type_name());
        Some(if field.type_name() == ".pg_query.Node" {
            Target::Node
        } else if let Some(variant) = self.variant_of.get(&ty) {
            Target::Variant(variant, ty)
        } else {
            Target::Plain(ty)
        })
    }
}

fn walk_fn(ty: &str, mutable: bool) -> String {
    format!(
        "walk_{}{}",
        if mutable { "mut_" } else { "" },
        ty.to_snake_case()
    )
}

/// Statements visiting one value `x` of the field's message type.
fn visit(target: &Target<'_>, mutable: bool) -> String {
    match (target, mutable) {
        (Target::Node, false) => "visit_node(x, out);".into(),
        (Target::Node, true) => "visit_node_mut(x, out);".into(),
        (Target::Variant(variant, ty), false) => {
            format!("let x: &'a protobuf::{ty} = x; out(NodeRef::{variant}(x));")
        }
        (Target::Variant(variant, ty), true) => {
            format!("let x: &mut protobuf::{ty} = x; out(NodeMut::{variant}(x));")
        }
        (Target::Plain(ty), false) => {
            format!(
                "let x: &'a protobuf::{ty} = x; {}(x, out);",
                walk_fn(ty, false)
            )
        }
        (Target::Plain(ty), true) => format!(
            "let x: &mut protobuf::{ty} = x; unsafe {{ {}(x, out) }};",
            walk_fn(ty, true)
        ),
    }
}

fn walkers(fds: &FileDescriptorSet) -> String {
    let model = Model::new(fds);
    let mut s = String::from(HEADER);
    s.push_str(
        "//! Views over the `Node` oneof and the child walkers behind\n\
         //! `nodes()` / `nodes_mut()`.\n\n\
         #![allow(clippy::all, dead_code, unused_variables)]\n\n\
         use crate::protobuf;\n\n",
    );

    // NodeRef / NodeMut.
    s.push_str(
        "/// A borrowed view of one AST node, by kind.\n\
         #[derive(Debug, Clone, Copy)]\npub enum NodeRef<'a> {\n",
    );
    for (variant, ty) in &model.variants {
        writeln!(s, "    {variant}(&'a protobuf::{ty}),").unwrap();
    }
    s.push_str(
        "}\n\n/// A raw mutable pointer to one AST node, by kind (see `nodes_mut`).\n\
         #[derive(Debug, Clone, Copy)]\npub enum NodeMut {\n",
    );
    for (variant, ty) in &model.variants {
        writeln!(s, "    {variant}(*mut protobuf::{ty}),").unwrap();
    }
    s.push_str("}\n\n");

    // Conversions from the oneof.
    s.push_str(
        "impl protobuf::node::Node {\n    /// This node as a [`NodeRef`].\n    \
         pub fn to_ref(&self) -> NodeRef<'_> {\n        match self {\n",
    );
    for (variant, ty) in &model.variants {
        writeln!(
            s,
            "            Self::{variant}(x) => {{ let x: &protobuf::{ty} = x; NodeRef::{variant}(x) }}"
        )
        .unwrap();
    }
    s.push_str(
        "        }\n    }\n\n    /// This node as a [`NodeMut`] pointer.\n    \
         pub fn to_mut(&mut self) -> NodeMut {\n        match self {\n",
    );
    for (variant, ty) in &model.variants {
        writeln!(
            s,
            "            Self::{variant}(x) => {{ let x: &mut protobuf::{ty} = x; NodeMut::{variant}(x) }}"
        )
        .unwrap();
    }
    s.push_str("        }\n    }\n}\n\n");

    // Dispatch.
    s.push_str(
        "/// Call `out` on every direct child node of `node`.\n\
         pub(crate) fn children<'a>(node: NodeRef<'a>, out: &mut dyn FnMut(NodeRef<'a>)) {\n    \
         match node {\n",
    );
    for (variant, ty) in &model.variants {
        writeln!(
            s,
            "        NodeRef::{variant}(m) => {}(m, out),",
            walk_fn(ty, false)
        )
        .unwrap();
    }
    s.push_str(
        "    }\n}\n\n/// Call `out` on every direct child node of `node`.\n///\n\
         /// # Safety\n/// `node` must point to a live node no one else accesses.\n\
         pub(crate) unsafe fn children_mut(node: NodeMut, out: &mut dyn FnMut(NodeMut)) {\n    \
         match node {\n",
    );
    for (variant, ty) in &model.variants {
        writeln!(
            s,
            "        NodeMut::{variant}(m) => unsafe {{ {}(m, out) }},",
            walk_fn(ty, true)
        )
        .unwrap();
    }
    s.push_str(
        "    }\n}\n\n\
         fn visit_node<'a>(n: &'a protobuf::Node, out: &mut dyn FnMut(NodeRef<'a>)) {\n    \
         if let Some(e) = &n.node { out(e.to_ref()); }\n}\n\n\
         fn visit_node_mut(n: &mut protobuf::Node, out: &mut dyn FnMut(NodeMut)) {\n    \
         if let Some(e) = &mut n.node { out(e.to_mut()); }\n}\n\n",
    );

    // One walker per message.
    for m in &model.messages {
        if m.name() == "Node" {
            continue;
        }
        let ty = type_ident(m.name());
        for mutable in [false, true] {
            let body = message_body(&model, m, mutable);
            if mutable {
                writeln!(
                    s,
                    "unsafe fn {}(m: *mut protobuf::{ty}, out: &mut dyn FnMut(NodeMut)) {{\n    \
                     let m = unsafe {{ &mut *m }};\n{body}}}\n",
                    walk_fn(&ty, true)
                )
                .unwrap();
            } else {
                writeln!(
                    s,
                    "fn {}<'a>(m: &'a protobuf::{ty}, out: &mut dyn FnMut(NodeRef<'a>)) {{\n{body}}}\n",
                    walk_fn(&ty, false)
                )
                .unwrap();
            }
        }
    }
    s
}

/// The statements of one message's walker.
fn message_body(model: &Model<'_>, m: &DescriptorProto, mutable: bool) -> String {
    let (amp, iter) = if mutable {
        ("&mut ", "&mut ")
    } else {
        ("&", "&")
    };
    let mut body = String::new();
    // Oneofs, grouped by declaration.
    let mut oneofs: Vec<(String, Vec<&FieldDescriptorProto>)> = m
        .oneof_decl
        .iter()
        .map(|o| (o.name().to_string(), Vec::new()))
        .collect();
    for field in &m.field {
        let Some(target) = model.target(field) else {
            continue;
        };
        if let Some(i) = field.oneof_index
            && !field.proto3_optional()
        {
            oneofs[i as usize].1.push(field);
            continue;
        }
        let name = field_ident(field.name());
        let visit = visit(&target, mutable);
        if field.label() == Label::Repeated {
            writeln!(body, "    for x in {iter}m.{name} {{ {visit} }}").unwrap();
        } else {
            writeln!(body, "    if let Some(x) = {amp}m.{name} {{ {visit} }}").unwrap();
        }
    }
    let module = m.name().to_snake_case();
    for (oneof, fields) in oneofs {
        if fields.is_empty() {
            continue;
        }
        let enum_ty = oneof.to_upper_camel_case();
        writeln!(body, "    match {amp}m.{} {{", field_ident(&oneof)).unwrap();
        for field in fields {
            let target = model.target(field).expect("message field");
            writeln!(
                body,
                "        Some(protobuf::{module}::{enum_ty}::{}(x)) => {{ {} }}",
                field.name().to_upper_camel_case(),
                visit(&target, mutable)
            )
            .unwrap();
        }
        body.push_str("        _ => {}\n    }\n");
    }
    body
}

/// The `(struct, field)` pairs PostgreSQL's `equal()` doesn't compare: fields
/// of type `ParseLoc` (source positions) and fields marked `equal_ignore`, as
/// declared in `parsenodes.h` / `primnodes.h`. Field names are PostgreSQL's,
/// which the `.proto` keeps as each field's `json_name`.
fn equal_ignored(headers: &Path) -> HashSet<(String, String)> {
    let mut out = HashSet::new();
    for file in ["parsenodes.h", "primnodes.h"] {
        let path = headers.join(file);
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
        let text = strip_c_comments(&text);
        let mut rest = text.as_str();
        while let Some(i) = rest.find("typedef struct ") {
            rest = &rest[i + "typedef struct ".len()..];
            let name: String = rest
                .chars()
                .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                .collect();
            let (Some(open), Some(close)) = (rest.find('{'), rest.find("\n}")) else {
                break;
            };
            if open > close {
                continue;
            }
            for decl in rest[open + 1..close].split(';') {
                let decl = decl.trim();
                let ignore =
                    decl.contains("equal_ignore") && !decl.contains("equal_ignore_if_zero");
                if !(decl.starts_with("ParseLoc") || ignore) {
                    continue;
                }
                // Drop `pg_node_attr(...)`; the field is then the last word.
                let bare = match decl.find("pg_node_attr") {
                    Some(k) => &decl[..k],
                    None => decl,
                };
                if let Some(field) = bare
                    .split(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
                    .rfind(|w| !w.is_empty())
                {
                    out.insert((name.clone(), field.to_string()));
                }
            }
            rest = &rest[close..];
        }
    }
    assert!(
        out.contains(&("A_Expr".into(), "location".into())),
        "no ParseLoc fields found in the PostgreSQL headers"
    );
    out
}

fn strip_c_comments(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(i) = rest.find("/*") {
        out.push_str(&rest[..i]);
        rest = match rest[i..].find("*/") {
            Some(j) => &rest[i + j + 2..],
            None => "",
        };
    }
    out.push_str(rest);
    out.lines()
        .map(|l| l.split("//").next().unwrap_or(""))
        .collect::<Vec<_>>()
        .join("\n")
}

const EQUAL_PRELUDE: &str = r#"//! PostgreSQL's `equal()` (equalfuncs.c) over the AST: two trees are equal
//! when every field is, except source locations and the fields PostgreSQL
//! marks `equal_ignore`.

#![allow(clippy::all, unused_variables)]

use crate::protobuf;

/// Structural equality of AST values, as PostgreSQL's `equal()`.
pub trait Equal {
    fn equal(&self, other: &Self) -> bool;

    /// Append the value's key: a string over the fields `equal()` compares,
    /// the same for two values exactly when they are `equal()` — what to
    /// hash or store in place of the value. Every key is self-delimiting
    /// (a scalar ends in `;`, a message is braced, a list bracketed), so a
    /// sequence of keys reads back one way.
    fn equal_key(&self, out: &mut String);
}

impl<T: Equal> Equal for Option<T> {
    fn equal(&self, other: &Self) -> bool {
        match (self, other) {
            (Some(a), Some(b)) => a.equal(b),
            (None, None) => true,
            _ => false,
        }
    }

    fn equal_key(&self, out: &mut String) {
        match self {
            Some(a) => {
                out.push('?');
                a.equal_key(out);
            }
            None => out.push('~'),
        }
    }
}

impl<T: Equal> Equal for Box<T> {
    fn equal(&self, other: &Self) -> bool {
        (**self).equal(other)
    }

    fn equal_key(&self, out: &mut String) {
        (**self).equal_key(out)
    }
}

impl<T: Equal> Equal for Vec<T> {
    fn equal(&self, other: &Self) -> bool {
        self.len() == other.len() && self.iter().zip(other).all(|(a, b)| a.equal(b))
    }

    fn equal_key(&self, out: &mut String) {
        out.push('[');
        for a in self {
            a.equal_key(out);
        }
        out.push(']');
    }
}

macro_rules! scalar {
    ($($t:ty),*) => {$(
        impl Equal for $t {
            fn equal(&self, other: &Self) -> bool {
                self == other
            }

            fn equal_key(&self, out: &mut String) {
                use std::fmt::Write;
                let _ = write!(out, "{self:?};");
            }
        }
    )*};
}

scalar!(bool, i32, i64, u32, u64, u8, f32, f64, String);

"#;

fn equality(fds: &FileDescriptorSet, ignored: &HashSet<(String, String)>) -> String {
    let model = Model::new(fds);
    let mut s = String::from(HEADER);
    s.push_str(EQUAL_PRELUDE);
    for m in &model.messages {
        // The summary API's records aren't AST.
        if !m.nested_type.is_empty() {
            continue;
        }
        let ty = type_ident(m.name());
        let mut fields: Vec<String> = Vec::new();
        let mut oneofs_done = HashSet::new();
        for field in &m.field {
            if let Some(i) = field.oneof_index
                && !field.proto3_optional()
            {
                if oneofs_done.insert(i) {
                    fields.push(field_ident(m.oneof_decl[i as usize].name()));
                }
                continue;
            }
            if ignored.contains(&(m.name().to_string(), field.json_name().to_string())) {
                continue;
            }
            fields.push(field_ident(field.name()));
        }
        let body = if fields.is_empty() {
            "true".to_string()
        } else {
            fields
                .iter()
                .map(|f| format!("self.{f}.equal(&other.{f})"))
                .collect::<Vec<_>>()
                .join(" && ")
        };
        let key: String = fields
            .iter()
            .map(|f| format!("        self.{f}.equal_key(out);\n"))
            .collect();
        writeln!(
            s,
            "impl Equal for protobuf::{ty} {{\n    fn equal(&self, other: &Self) -> bool {{\n        {body}\n    }}\n\n    fn equal_key(&self, out: &mut String) {{\n        out.push('{{');\n{key}        out.push('}}');\n    }}\n}}\n"
        )
        .unwrap();
        for (i, oneof) in m.oneof_decl.iter().enumerate() {
            let module = m.name().to_snake_case();
            let enum_ty = oneof.name().to_upper_camel_case();
            let mut arms = String::new();
            let mut key_arms = String::new();
            for field in m.field.iter().filter(|f| f.oneof_index == Some(i as i32)) {
                let v = field.name().to_upper_camel_case();
                writeln!(
                    arms,
                    "            (Self::{v}(a), Self::{v}(b)) => a.equal(b),"
                )
                .unwrap();
                writeln!(
                    key_arms,
                    "            Self::{v}(a) => {{\n                out.push_str(\"{v}(\");\n                a.equal_key(out);\n                out.push(')');\n            }}"
                )
                .unwrap();
            }
            writeln!(
                s,
                "impl Equal for protobuf::{module}::{enum_ty} {{\n    fn equal(&self, other: &Self) -> bool {{\n        #[allow(unreachable_patterns)]\n        match (self, other) {{\n{arms}            _ => false,\n        }}\n    }}\n\n    fn equal_key(&self, out: &mut String) {{\n        match self {{\n{key_arms}        }}\n    }}\n}}\n"
            )
            .unwrap();
        }
    }
    s
}
