//! Literal-content battery for the input-function validators in
//! `literal_input.rs` — bit/varbit, money, inet/cidr, macaddr, the
//! geometric family, tid/pg_lsn/xid, and the datetime input decoder.
//! Valid and invalid contents side by side, mirrored against the live PG
//! (outcome + error wording + SQLSTATE) by `analyze_checked`.
#![cfg(feature = "pg_sanity")]

#[path = "common/parity.rs"]
mod parity;

const SETUP: &str = "CREATE TABLE t (id INT PRIMARY KEY);";

const BATTERY: &[&str] = &[
    // ── bit / varbit ────────────────────────────────────────────────────
    "SELECT '101'::varbit",
    "SELECT 'x1F'::varbit",
    "SELECT 'b101'::varbit",
    "SELECT ''::varbit",
    "SELECT 'NaN'::varbit",
    "SELECT ' 42 '::varbit",
    "SELECT '0b101'::varbit",
    "SELECT '102'::varbit",
    "SELECT 'xFG'::varbit",
    "SELECT '101'::bit(3)",
    "SELECT '2'::bit(1)",
    // ── money ───────────────────────────────────────────────────────────
    "SELECT '123'::money",
    "SELECT '$123.45'::money",
    "SELECT '-$1,000.00'::money",
    "SELECT '($123)'::money",
    "SELECT '$-123'::money",
    "SELECT '  12  '::money",
    "SELECT 'hello'::money",
    "SELECT ''::money",
    "SELECT '(1,2]'::money",
    "SELECT '1.2.3'::money",
    "SELECT '9999999999999999999999'::money",
    // ── inet / cidr ─────────────────────────────────────────────────────
    "SELECT '192.168.0.1'::inet",
    "SELECT '192.168.0.1/24'::inet",
    "SELECT '::1'::inet",
    "SELECT 'fe80::1/64'::inet",
    "SELECT '::ffff:192.168.0.1'::inet",
    "SELECT '42'::inet",
    "SELECT '192.168'::inet",
    "SELECT '256.1.1.1'::inet",
    "SELECT '192.168.0.1/33'::inet",
    "SELECT 'hello'::inet",
    "SELECT '1:2:3:4:5:6:7:8'::inet",
    "SELECT '1:2:3:4:5:6:7:8:9'::inet",
    "SELECT '1::2::3'::inet",
    "SELECT '10/8'::cidr",
    "SELECT '10.1/16'::cidr",
    "SELECT '192.168.0.0/24'::cidr",
    "SELECT 'x/8'::cidr",
    // ── macaddr / macaddr8 ──────────────────────────────────────────────
    "SELECT 'aa:bb:cc:dd:ee:ff'::macaddr",
    "SELECT 'aa-bb-cc-dd-ee-ff'::macaddr",
    "SELECT 'aabb.ccdd.eeff'::macaddr",
    "SELECT 'aabbccddeeff'::macaddr",
    "SELECT 'aa:bb:cc:dd:ee'::macaddr",
    "SELECT ' 42 '::macaddr",
    "SELECT 'hello'::macaddr",
    "SELECT 'aa:bb:cc:dd:ee:ff:00:11'::macaddr8",
    "SELECT 'aa:bb:cc:dd:ee:ff'::macaddr8",
    "SELECT 'zz:bb:cc:dd:ee:ff'::macaddr8",
    // ── geometric ───────────────────────────────────────────────────────
    "SELECT '(1,2)'::point",
    "SELECT '1,2'::point",
    "SELECT '(NaN,NaN)'::point",
    "SELECT '(1.5e3,-2)'::point",
    "SELECT '3.14'::point",
    "SELECT 'hello'::point",
    "SELECT '((0,0),(1,1))'::box",
    "SELECT ' 42 '::box",
    "SELECT '[(0,0),(1,1)]'::lseg",
    "SELECT '(1,2)'::lseg",
    "SELECT '<(0,0),5>'::circle",
    "SELECT '(1,2)'::circle",
    "SELECT '{1,2,3}'::line",
    "SELECT '((0,0),(1,1))'::line",
    "SELECT '{1,2}'::line",
    "SELECT '((0,0),(1,1),(2,0))'::polygon",
    "SELECT '(1,2)'::path",
    "SELECT '(1,2,3)'::path",
    // ── tid / pg_lsn / xid ──────────────────────────────────────────────
    "SELECT '(0,1)'::tid",
    "SELECT '(0)'::tid",
    "SELECT '42'::tid",
    "SELECT '0/0'::pg_lsn",
    "SELECT 'AB/CDEF1234'::pg_lsn",
    "SELECT '0'::pg_lsn",
    "SELECT 'X/Y'::pg_lsn",
    "SELECT '42'::xid",
    "SELECT 'ff'::xid",
    "SELECT '42'::xid8",
    "SELECT '0x10'::xid8",
    "SELECT '0x10'::cid",
    "SELECT '0x10'::xid",
    "SELECT ''::money",
    // ── datetime tokenizer alphabet ─────────────────────────────────────
    "SELECT '2024-01-01'::date",
    "SELECT '(1,2]'::date",
    "SELECT '{1,2}'::timestamp",
    "SELECT '[1,]'::timestamptz",
    "SELECT '12:30:00'::time",
    "SELECT '{}'::timetz",
    "SELECT '1 day'::interval",
    // (Not `'[1,2)'`: under an `interval hour` typmod that decodes as
    // 1 day 2 hours, and the validator can't see the typmod.)
    "SELECT '[1,x)'::interval",
    "SELECT '2024-01-01 12:00 America/New_York'::timestamptz",
    "SELECT 'now()'::timestamptz",
    // ── jsonpath like_regex: patterns compiled by pg_regcomp ─────────────
    // Each pattern bare and with a flag string (i / q / sm / x / xq / an
    // invalid flag), valid and invalid alike.
    r#"SELECT '$ ? (@ like_regex "^a+b*c?$")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "^a+b*c?$" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a|b)+\\1")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a|b)+\\1" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?:ab){2,3}?")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?:ab){2,3}?" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{0,255}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{0,255}" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{,3}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{,3}" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "x{")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "x{" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[]a]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[]a]" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[^]a-]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[^]a-]" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:alpha:][:digit:]_]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:alpha:][:digit:]_]" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[.hyphen.]-[.period.]]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[.hyphen.]-[.period.]]" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[=e=]]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[=e=]]" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[\\d\\W]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[\\d\\W]" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:<:]]w[[:>:]]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:<:]]w[[:>:]]" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\mw\\M\\yx\\Y\\A\\Z")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\mw\\M\\yx\\Y\\A\\Z" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?=a)(?!b)(?<=c)(?<!d)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?=a)(?!b)(?<=c)(?<!d)" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?i)ABC")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?i)ABC" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?x) a b # c")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?x) a b # c" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?e))")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?e))" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?b)\\(a\\)\\1*")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?b)\\(a\\)\\1*" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?q)(((")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?q)(((" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "***=(((")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "***=(((" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "***:a+")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "***:a+" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a(?#note)b")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a(?#note)b" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\x41\\u0041\\U00000041\\0\\101\\cA")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\x41\\u0041\\U00000041\\0\\101\\cA" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a)\\10")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a)\\10" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\12")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\12" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\U7FFFFFFE")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\U7FFFFFFE" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[.NUL.]-[.DEL.]]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[.NUL.]-[.DEL.]]" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\e\\a\\B\\f\\v")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\e\\a\\B\\f\\v" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex ")")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex ")" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a)" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?:a")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?:a" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?=a")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?=a" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[a")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[a" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[]" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[^]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[^]" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{1")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{1" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{1a}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{1a}" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{256}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{256}" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{2,1}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{2,1}" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{1,2,3}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{1,2,3}" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "*")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "*" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a**")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a**" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "^*")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "^*" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a|+")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a|+" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?=a)*")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?=a)*" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{2}{3}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{2}{3}" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a(?i)b")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a(?i)b" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?<x)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?<x)" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?P<n>a)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?P<n>a)" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "***")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "***" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "***?")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "***?" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?z)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?z)" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?i" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\g")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\g" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\x" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\u12")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\u12" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\UFFFFFFFF")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\UFFFFFFFF" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\99")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\99" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[\\y]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[\\y]" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[\\1]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[\\1]" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\1")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\1" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a\\1)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a\\1)" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a)(?=\\1)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a)(?=\\1)" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a)(?<!x\\1)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a)(?<!x\\1)" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[z-a]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[z-a]" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[a-b-c]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[a-b-c]" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[a-\\d]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[a-\\d]" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:alpha:]-z]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:alpha:]-z]" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:foo:]]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:foo:]]" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:ALPHA:]]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:ALPHA:]]" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[.foo.]]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[.foo.]]" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[=ab=]]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[=ab=]]" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[.a.]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[.a.]" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?e)(?:a)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?e)(?:a)" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?b)\\(")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?b)\\(" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?b)a\\{1")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?b)a\\{1" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?b)a\\{1}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?b)a\\{1}" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?x)a{1 x}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?x)a{1 x}" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\c")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\c" flag "x")'::jsonpath"#,
    // ── datetime decoding (datetime.c port: date, time, timetz, timestamp,
    //    timestamptz, interval — valid and invalid side by side) ───────────
    "SELECT '2024-01-15'::date",
    "SELECT '2024-1-5'::date",
    "SELECT '01/15/2024'::date",
    "SELECT '15/01/2024'::date",
    "SELECT '2024.015'::date",
    "SELECT '20240115'::date",
    "SELECT '240115'::date",
    "SELECT 'Jan 15 2024'::date",
    "SELECT '15 Jan 2024'::date",
    "SELECT 'January 15, 2024'::date",
    "SELECT 'jan-15-2024'::date",
    "SELECT '15-jan-2024'::date",
    "SELECT '2024-jan-15'::date",
    "SELECT '15jan2024'::date",
    "SELECT '2024-02-29'::date",
    "SELECT '2023-02-29'::date",
    "SELECT '1900-02-29'::date",
    "SELECT '2000-02-29'::date",
    "SELECT '2024-13-01'::date",
    "SELECT '2024-00-10'::date",
    "SELECT '2024-04-31'::date",
    "SELECT '0000-01-01'::date",
    "SELECT '99-01-01'::date",
    "SELECT '69-01-01'::date",
    "SELECT '2024-01-15 BC'::date",
    "SELECT '0 BC'::date",
    "SELECT 'J2451187'::date",
    "SELECT 'J 2451187'::date",
    "SELECT 'J-1'::date",
    "SELECT 'epoch'::date",
    "SELECT 'infinity'::date",
    "SELECT '-infinity'::date",
    "SELECT 'today'::date",
    "SELECT 'yesterday'::date",
    "SELECT 'tomorrow'::date",
    "SELECT 'allballs'::date",
    "SELECT 'Monday 2024-01-15'::date",
    "SELECT '2024-01-15 12:30'::date",
    "SELECT '2024-01-15 25:00'::date",
    "SELECT '5874897-12-31'::date",
    "SELECT '5874898-01-01'::date",
    "SELECT '4714-11-24 BC'::date",
    "SELECT '4714-11-23 BC'::date",
    "SELECT '2024-01-15 12:00 America/Sao_Paulo'::date",
    "SELECT '2024-01-15 12:00 Foo/Bar'::date",
    "SELECT '12:00'::date",
    "SELECT '2024'::date",
    "SELECT '2024-01'::date",
    "SELECT '01-32-2024'::date",
    "SELECT '2024.366'::date",
    "SELECT '2023.366'::date",
    "SELECT '1.2.3'::date",
    "SELECT '2024-01-15 xyz'::date",
    "SELECT ''::date",
    "SELECT '12:30'::time",
    "SELECT '12:30:45'::time",
    "SELECT '12:30:45.5'::time",
    "SELECT '12:61'::time",
    "SELECT '25:00'::time",
    "SELECT '24:00'::time",
    "SELECT '24:00:00'::time",
    "SELECT '24:00:01'::time",
    "SELECT '23:59:60'::time",
    "SELECT '23:59:61'::time",
    "SELECT '12:30 am'::time",
    "SELECT '12:30 PM'::time",
    "SELECT '13:00 pm'::time",
    "SELECT '0:00 am'::time",
    "SELECT '1230'::time",
    "SELECT '123045'::time",
    "SELECT '123045.5'::time",
    "SELECT '12'::time",
    "SELECT '12.5'::time",
    "SELECT '12:30 +05'::time",
    "SELECT '12:30 UTC'::time",
    "SELECT '12:30 PST'::time",
    "SELECT 'now'::time",
    "SELECT 'allballs'::time",
    "SELECT 'epoch'::time",
    "SELECT '12:30 jan'::time",
    "SELECT 't12:30'::time",
    "SELECT '12:30:45.1234567'::time",
    "SELECT '12:'::time",
    "SELECT '12::30'::time",
    "SELECT '040506-08'::time",
    "SELECT '040506-25'::time",
    "SELECT '12:30 2024-01-15'::time",
    "SELECT '12:30 foo'::time",
    "SELECT '12:30+05'::timetz",
    "SELECT '12:30 -03:30'::timetz",
    "SELECT '12:30 +16'::timetz",
    "SELECT '12:30 +15:59'::timetz",
    "SELECT '12:30 +15:60'::timetz",
    "SELECT '12:30 UTC'::timetz",
    "SELECT '12:30 PST'::timetz",
    "SELECT '12:30 MSK'::timetz",
    "SELECT '12:30 America/Sao_Paulo'::timetz",
    "SELECT '2024-01-15 12:30 America/Sao_Paulo'::timetz",
    "SELECT '12:30 Etc/GMT+3'::timetz",
    "SELECT '12:30 Foo/Bar'::timetz",
    "SELECT '2024-01 12:30 MSK'::timetz",
    "SELECT '12:30 CEST DST'::timetz",
    "SELECT '12:30 MET DST'::timetz",
    "SELECT '12:30 DST'::timetz",
    "SELECT 'allballs'::timetz",
    "SELECT '12:30 foo+3'::timetz",
    "SELECT '2024-01-15 12:30:45'::timestamp",
    "SELECT '2024-01-15T12:30:45'::timestamp",
    "SELECT '20240115T123045'::timestamp",
    "SELECT '2024-01-15 t 123045'::timestamp",
    "SELECT 'yesterday 10:00'::timestamp",
    "SELECT 'today 25:00'::timestamp",
    "SELECT '2024-01-15 12:30:45.123456'::timestamp",
    "SELECT 'Mon Jan 15 12:30:45 2024'::timestamp",
    "SELECT '2024-01-15 12:30 BC'::timestamp",
    "SELECT '294276-12-31 23:59:59'::timestamp",
    "SELECT '294277-01-01'::timestamp",
    "SELECT '4714-11-24 BC'::timestamp",
    "SELECT '4714-11-23 BC'::timestamp",
    "SELECT '2024-01-15 256199'::timestamp",
    "SELECT '2024-01-15 12:30:45:67'::timestamp",
    "SELECT '2024-01-15 12:'::timestamp",
    "SELECT 'allballs'::timestamp",
    "SELECT 'now()'::timestamp",
    "SELECT '2024-01-15 12h30'::timestamp",
    "SELECT 'J2451187.5'::timestamp",
    "SELECT 'julian 2451187'::timestamp",
    "SELECT '2024-01-15 12:30 xday'::timestamp",
    "SELECT '2024-01-15 12:30:45+05'::timestamptz",
    "SELECT '2024-01-15 12:30:45-03:30'::timestamptz",
    "SELECT '2024-01-15T12:30:45Z'::timestamptz",
    "SELECT '2024-01-15 12:30:45 UTC'::timestamptz",
    "SELECT '2024-01-15 12:30:45 America/Sao_Paulo'::timestamptz",
    "SELECT '2024-01-15 12:30:45 america/new_york'::timestamptz",
    "SELECT '2024-01-15 12:30:45 PST'::timestamptz",
    "SELECT '2024-01-15 12:30:45 CEST'::timestamptz",
    "SELECT '2024-01-15 12:30:45 MSK'::timestamptz",
    "SELECT '2024-01-15 12:30:45 MET DST'::timestamptz",
    "SELECT '2024-01-15 12:30:45 CEST DST'::timestamptz",
    "SELECT '2024-01-15 12:30:45+16'::timestamptz",
    "SELECT '2024-01-15 12:30:45+15:59'::timestamptz",
    "SELECT '2024-01-15 12:30:45+15:60'::timestamptz",
    "SELECT '2024-01-15 12:30:45 UTC+3'::timestamptz",
    "SELECT '2024-01-15 12:30:45 foo+3'::timestamptz",
    "SELECT '2024-01-15 12:30:45 Etc/GMT+3'::timestamptz",
    "SELECT '2024-01-15 12:30:45 Foo/Bar'::timestamptz",
    "SELECT '2024-01-15 12:30:45 xyz'::timestamptz",
    "SELECT '294276-12-31 23:59:59+00'::timestamptz",
    "SELECT '294276-12-31 23:59:59 -02'::timestamptz",
    "SELECT '4714-11-24 00:00 BC +00'::timestamptz",
    "SELECT '4714-11-24 00:00 BC +02'::timestamptz",
    "SELECT 'Jan 15 123045-08 2024'::timestamptz",
    "SELECT '1 day'::timestamptz",
    "SELECT 'now'::timestamptz",
    "SELECT 'epoch'::timestamptz",
    "SELECT '-infinity'::timestamptz",
    "SELECT '+infinity'::timestamptz",
    "SELECT '1 day'::interval",
    "SELECT '1 fortnight'::interval",
    "SELECT '1 xday'::interval",
    "SELECT '1.5 weeks'::interval",
    "SELECT '1 week 2 days'::interval",
    "SELECT '@ 1 day ago'::interval",
    "SELECT '1 day ago'::interval",
    "SELECT '1 ago'::interval",
    "SELECT '-1 day'::interval",
    "SELECT '1-2'::interval",
    "SELECT '1-12'::interval",
    "SELECT '-1-2'::interval",
    "SELECT '1 2:03:04'::interval",
    "SELECT '1 -2:03:04'::interval",
    "SELECT '2:03:04'::interval",
    "SELECT '1 d 2 h 3 m 4 s'::interval",
    "SELECT '1 mon'::interval",
    "SELECT '1 yr 2 mons'::interval",
    "SELECT '1 century'::interval",
    "SELECT '1 millennium'::interval",
    "SELECT '1 decade'::interval",
    "SELECT '1 ms'::interval",
    "SELECT '1 us'::interval",
    "SELECT '1 microseconds'::interval",
    "SELECT '1 millisecondsxyz'::interval",
    "SELECT '1 qtr'::interval",
    "SELECT '1 day day'::interval",
    "SELECT 'day'::interval",
    "SELECT '1'::interval",
    "SELECT '1.5'::interval",
    "SELECT '2147483647 days'::interval",
    "SELECT '2147483648 days'::interval",
    "SELECT '178956970 years'::interval",
    "SELECT '178956971 years'::interval",
    "SELECT 'P1Y2M3DT4H5M6S'::interval",
    "SELECT 'P1Y2M3DT4H5M6.5S'::interval",
    "SELECT 'P1.5Y'::interval",
    "SELECT 'PT1H'::interval",
    "SELECT 'PT'::interval",
    "SELECT 'P'::interval",
    "SELECT 'P1W'::interval",
    "SELECT 'P0001-02-03T04:05:06'::interval",
    "SELECT 'P00010203T040506'::interval",
    "SELECT 'PT040506'::interval",
    "SELECT 'P1Y-2M'::interval",
    "SELECT 'p1d'::interval",
    "SELECT 'P-1D'::interval",
    "SELECT 'P1e3D'::interval",
    "SELECT 'P1e20D'::interval",
    "SELECT 'P-infD'::interval",
    "SELECT 'P1Y1Y'::interval",
    "SELECT 'infinity'::interval",
    "SELECT '-infinity'::interval",
    "SELECT 'infinity ago'::interval",
    "SELECT '1 day infinity'::interval",
    "SELECT 'now'::interval",
    "SELECT 'epoch'::interval",
    "SELECT '1 at'::interval",
    "SELECT '1 jan'::interval",
    "SELECT '1 t'::interval",
    "SELECT '1 mm'::interval",
    "SELECT '9223372036854775807'::interval",
    "SELECT '99999999999999999999'::interval",
    "SELECT '1:2:3:4'::interval",
    "SELECT '100:30'::interval",
    "SELECT '12:30:45.123'::interval",
    "SELECT '-12:30:45'::interval",
    "SELECT '1 days 1 days'::interval",
    "SELECT '2 weeks ago'::interval",
    "SELECT ''::interval",
];

#[test]
fn literal_battery() {
    parity::assert_battery_parity(SETUP, BATTERY, "literal shapes");
}
