//! Literal-content battery for the input-function validators in
//! `literal_input.rs` — bit/varbit, money, inet/cidr, macaddr, the
//! geometric family, tid/pg_lsn/xid, and the datetime tokenizer-alphabet
//! rule. Valid and invalid contents side by side, mirrored against the
//! live PG (outcome + error wording + SQLSTATE) by `analyze_checked`.
#![cfg(feature = "pg_sanity")]

#[path = "common/parity.rs"]
mod parity;

const SETUP: &str = "CREATE TABLE t (id INT PRIMARY KEY);";

const BATTERY: &[&str] = &[
    // ── bit / varbit ────────────────────────────────────────────────────
    "SELECT '101'::varbit",
    "SELECT 'x1F'::varbit",
    "SELECT 'b101'::varbit",
    "SELECT ''::varbit",
    "SELECT 'NaN'::varbit",
    "SELECT ' 42 '::varbit",
    "SELECT '0b101'::varbit",
    "SELECT '102'::varbit",
    "SELECT 'xFG'::varbit",
    "SELECT '101'::bit(3)",
    "SELECT '2'::bit(1)",
    // ── money ───────────────────────────────────────────────────────────
    "SELECT '123'::money",
    "SELECT '$123.45'::money",
    "SELECT '-$1,000.00'::money",
    "SELECT '($123)'::money",
    "SELECT '$-123'::money",
    "SELECT '  12  '::money",
    "SELECT 'hello'::money",
    "SELECT ''::money",
    "SELECT '(1,2]'::money",
    "SELECT '1.2.3'::money",
    "SELECT '9999999999999999999999'::money",
    // ── inet / cidr ─────────────────────────────────────────────────────
    "SELECT '192.168.0.1'::inet",
    "SELECT '192.168.0.1/24'::inet",
    "SELECT '::1'::inet",
    "SELECT 'fe80::1/64'::inet",
    "SELECT '::ffff:192.168.0.1'::inet",
    "SELECT '42'::inet",
    "SELECT '192.168'::inet",
    "SELECT '256.1.1.1'::inet",
    "SELECT '192.168.0.1/33'::inet",
    "SELECT 'hello'::inet",
    "SELECT '1:2:3:4:5:6:7:8'::inet",
    "SELECT '1:2:3:4:5:6:7:8:9'::inet",
    "SELECT '1::2::3'::inet",
    "SELECT '10/8'::cidr",
    "SELECT '10.1/16'::cidr",
    "SELECT '192.168.0.0/24'::cidr",
    "SELECT 'x/8'::cidr",
    // ── macaddr / macaddr8 ──────────────────────────────────────────────
    "SELECT 'aa:bb:cc:dd:ee:ff'::macaddr",
    "SELECT 'aa-bb-cc-dd-ee-ff'::macaddr",
    "SELECT 'aabb.ccdd.eeff'::macaddr",
    "SELECT 'aabbccddeeff'::macaddr",
    "SELECT 'aa:bb:cc:dd:ee'::macaddr",
    "SELECT ' 42 '::macaddr",
    "SELECT 'hello'::macaddr",
    "SELECT 'aa:bb:cc:dd:ee:ff:00:11'::macaddr8",
    "SELECT 'aa:bb:cc:dd:ee:ff'::macaddr8",
    "SELECT 'zz:bb:cc:dd:ee:ff'::macaddr8",
    // ── geometric ───────────────────────────────────────────────────────
    "SELECT '(1,2)'::point",
    "SELECT '1,2'::point",
    "SELECT '(NaN,NaN)'::point",
    "SELECT '(1.5e3,-2)'::point",
    "SELECT '3.14'::point",
    "SELECT 'hello'::point",
    "SELECT '((0,0),(1,1))'::box",
    "SELECT ' 42 '::box",
    "SELECT '[(0,0),(1,1)]'::lseg",
    "SELECT '(1,2)'::lseg",
    "SELECT '<(0,0),5>'::circle",
    "SELECT '(1,2)'::circle",
    "SELECT '{1,2,3}'::line",
    "SELECT '((0,0),(1,1))'::line",
    "SELECT '{1,2}'::line",
    "SELECT '((0,0),(1,1),(2,0))'::polygon",
    "SELECT '(1,2)'::path",
    "SELECT '(1,2,3)'::path",
    // ── tid / pg_lsn / xid ──────────────────────────────────────────────
    "SELECT '(0,1)'::tid",
    "SELECT '(0)'::tid",
    "SELECT '42'::tid",
    "SELECT '0/0'::pg_lsn",
    "SELECT 'AB/CDEF1234'::pg_lsn",
    "SELECT '0'::pg_lsn",
    "SELECT 'X/Y'::pg_lsn",
    "SELECT '42'::xid",
    "SELECT 'ff'::xid",
    "SELECT '42'::xid8",
    "SELECT '0x10'::xid8",
    "SELECT '0x10'::cid",
    "SELECT '0x10'::xid",
    "SELECT ''::money",
    // ── datetime tokenizer alphabet ─────────────────────────────────────
    "SELECT '2024-01-01'::date",
    "SELECT '(1,2]'::date",
    "SELECT '{1,2}'::timestamp",
    "SELECT '[1,]'::timestamptz",
    "SELECT '12:30:00'::time",
    "SELECT '{}'::timetz",
    "SELECT '1 day'::interval",
    "SELECT '[1,2)'::interval",
    "SELECT '2024-01-01 12:00 America/New_York'::timestamptz",
    "SELECT 'now()'::timestamptz",
    // ── jsonpath like_regex: patterns compiled by pg_regcomp ─────────────
    // Each pattern bare and with a flag string (i / q / sm / x / xq / an
    // invalid flag), valid and invalid alike.
    r#"SELECT '$ ? (@ like_regex "^a+b*c?$")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "^a+b*c?$" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a|b)+\\1")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a|b)+\\1" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?:ab){2,3}?")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?:ab){2,3}?" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{0,255}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{0,255}" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{,3}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{,3}" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "x{")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "x{" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[]a]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[]a]" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[^]a-]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[^]a-]" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:alpha:][:digit:]_]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:alpha:][:digit:]_]" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[.hyphen.]-[.period.]]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[.hyphen.]-[.period.]]" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[=e=]]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[=e=]]" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[\\d\\W]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[\\d\\W]" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:<:]]w[[:>:]]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:<:]]w[[:>:]]" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\mw\\M\\yx\\Y\\A\\Z")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\mw\\M\\yx\\Y\\A\\Z" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?=a)(?!b)(?<=c)(?<!d)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?=a)(?!b)(?<=c)(?<!d)" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?i)ABC")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?i)ABC" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?x) a b # c")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?x) a b # c" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?e))")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?e))" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?b)\\(a\\)\\1*")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?b)\\(a\\)\\1*" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?q)(((")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?q)(((" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "***=(((")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "***=(((" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "***:a+")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "***:a+" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a(?#note)b")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a(?#note)b" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\x41\\u0041\\U00000041\\0\\101\\cA")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\x41\\u0041\\U00000041\\0\\101\\cA" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a)\\10")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a)\\10" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\12")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\12" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\U7FFFFFFE")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\U7FFFFFFE" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[.NUL.]-[.DEL.]]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[.NUL.]-[.DEL.]]" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\e\\a\\B\\f\\v")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\e\\a\\B\\f\\v" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex ")")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex ")" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a)" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?:a")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?:a" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?=a")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?=a" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[a")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[a" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[]" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[^]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[^]" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{1")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{1" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{1a}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{1a}" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{256}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{256}" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{2,1}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{2,1}" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{1,2,3}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{1,2,3}" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "*")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "*" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a**")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a**" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "^*")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "^*" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a|+")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a|+" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?=a)*")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?=a)*" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{2}{3}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a{2}{3}" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a(?i)b")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "a(?i)b" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?<x)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?<x)" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?P<n>a)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?P<n>a)" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "***")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "***" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "***?")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "***?" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?z)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?z)" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?i" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\g")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\g" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\x" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\u12")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\u12" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\UFFFFFFFF")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\UFFFFFFFF" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\99")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\99" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[\\y]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[\\y]" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[\\1]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[\\1]" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\1")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\1" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a\\1)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a\\1)" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a)(?=\\1)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a)(?=\\1)" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a)(?<!x\\1)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(a)(?<!x\\1)" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[z-a]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[z-a]" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[a-b-c]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[a-b-c]" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[a-\\d]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[a-\\d]" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:alpha:]-z]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:alpha:]-z]" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:foo:]]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:foo:]]" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:ALPHA:]]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[:ALPHA:]]" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[.foo.]]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[.foo.]]" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[=ab=]]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[=ab=]]" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[.a.]")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "[[.a.]" flag "x")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?e)(?:a)")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?e)(?:a)" flag "xq")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?b)\\(")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?b)\\(" flag "iz")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?b)a\\{1")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?b)a\\{1" flag "i")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?b)a\\{1}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?b)a\\{1}" flag "q")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?x)a{1 x}")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "(?x)a{1 x}" flag "sm")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\c")'::jsonpath"#,
    r#"SELECT '$ ? (@ like_regex "\\c" flag "x")'::jsonpath"#,
];

#[test]
fn literal_battery() {
    parity::assert_battery_parity(SETUP, BATTERY, "literal shapes");
}
