use tokio_postgres::Row;
use tokio_postgres::types::ToSql;

use crate::copy::{CopyRow, column_types, write_rows};
use crate::stream::RowStream;

/// Abstraction over types that can execute SQL queries against PostgreSQL.
///
/// You typically do not interact with this trait directly. The [`sql!`](crate::query)
/// macro generates code that is generic over `Executor`, so the same query expression
/// works whether you pass a connection pool, a pooled client, a raw client, or a
/// transaction.
///
/// # Implementations
///
/// | Type | Behavior |
/// |------|----------|
/// | `deadpool_postgres::Pool` | Acquires a connection per call, returns it on completion |
/// | `deadpool_postgres::Object` | Delegates to the inner `tokio_postgres::Client` |
/// | `deadpool_postgres::Transaction<'_>` | Delegates to the inner `tokio_postgres::Transaction` |
/// | `tokio_postgres::Client` | Executes directly on the client |
/// | `tokio_postgres::Transaction<'_>` | Executes within the open transaction |
///
/// # Examples
///
/// Both pool and transaction work transparently:
///
/// ```rust,ignore
/// use typedpg::query;
///
/// # async fn example(pool: &deadpool_postgres::Pool) -> Result<(), typedpg::Error> {
/// // Using the pool directly
/// let users = sql!(pool, "SELECT id, name FROM users").fetch_all().await?;
///
/// // Using a transaction
/// let mut client = pool.get().await.map_err(|e| typedpg::Error::Pool(e.to_string()))?;
/// let tx = client.transaction().await?;
/// sql!(&tx, "DELETE FROM users WHERE id = $id", id = 1).execute().await?;
/// tx.commit().await?;
/// # Ok(())
/// # }
/// ```
pub trait Executor: Sync {
    /// Executes a query and returns all resulting rows.
    ///
    /// Used internally by the `fetch_all` and `fetch_one`/`fetch_optional` methods
    /// generated by `sql!`.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Database`](crate::Error::Database) if the query fails, or
    /// [`Error::Pool`](crate::Error::Pool) if a pooled implementation cannot acquire
    /// a connection.
    fn query<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> impl std::future::Future<Output = Result<Vec<Row>, crate::Error>> + Send + 'a;

    /// Executes a statement and returns the number of affected rows.
    ///
    /// Used internally by the `execute` method generated by `sql!` for
    /// `INSERT`, `UPDATE`, and `DELETE` statements.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Database`](crate::Error::Database) if the statement fails, or
    /// [`Error::Pool`](crate::Error::Pool) if a pooled implementation cannot acquire
    /// a connection.
    fn execute<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> impl std::future::Future<Output = Result<u64, crate::Error>> + Send + 'a;

    /// Executes a query and returns its rows as a stream, as the server
    /// sends them.
    ///
    /// Used internally by the `fetch_stream` methods generated by `sql!`.
    /// The default implementation fetches every row first; the
    /// implementations in this crate stream them, a pooled one keeping its
    /// connection until the stream is dropped.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Database`](crate::Error::Database) if the query fails, or
    /// [`Error::Pool`](crate::Error::Pool) if a pooled implementation cannot acquire
    /// a connection. Errors while reading rows come through the stream.
    fn query_stream<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> impl std::future::Future<Output = Result<RowStream, crate::Error>> + Send + 'a {
        async move { Ok(RowStream::from_rows(self.query(sql, params).await?)) }
    }

    /// Runs `copy_sql` (a binary `COPY ... FROM STDIN`) feeding it `rows`,
    /// and returns the number of rows copied. `describe_sql` is prepared
    /// only for the target columns' types.
    ///
    /// Used internally by `copy_in!`. The default implementation returns
    /// [`Error::Unsupported`](crate::Error::Unsupported); every executor in
    /// this crate implements it.
    ///
    /// # Errors
    ///
    /// [`Error::Database`](crate::Error::Database) if the server refuses the
    /// COPY or a row, the error a row's conversion raised, or
    /// [`Error::Pool`](crate::Error::Pool) if no connection can be acquired.
    /// On error the COPY is aborted: no row is kept.
    fn copy_in<'a, I>(
        &'a self,
        describe_sql: &'a str,
        copy_sql: &'a str,
        rows: I,
    ) -> impl std::future::Future<Output = Result<u64, crate::Error>> + Send + 'a
    where
        I: Iterator<Item = Result<CopyRow, crate::Error>> + Send + 'a,
    {
        let _ = (describe_sql, copy_sql, rows);
        async move {
            Err(crate::Error::Unsupported(
                "this executor does not implement COPY".into(),
            ))
        }
    }
}

impl<T: Executor + Sync> Executor for &T {
    async fn query<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> Result<Vec<Row>, crate::Error> {
        (**self).query(sql, params).await
    }

    async fn execute<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> Result<u64, crate::Error> {
        (**self).execute(sql, params).await
    }

    async fn query_stream<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> Result<RowStream, crate::Error> {
        (**self).query_stream(sql, params).await
    }

    // Not an `async fn`: forwarding the inner future sidesteps Rust 1.88
    // (the MSRV) rejecting the generic's lifetime bound in one
    // (rust#100013).
    fn copy_in<'a, I>(
        &'a self,
        describe_sql: &'a str,
        copy_sql: &'a str,
        rows: I,
    ) -> impl std::future::Future<Output = Result<u64, crate::Error>> + Send + 'a
    where
        I: Iterator<Item = Result<CopyRow, crate::Error>> + Send + 'a,
    {
        (**self).copy_in(describe_sql, copy_sql, rows)
    }
}

impl Executor for tokio_postgres::Client {
    async fn query<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> Result<Vec<Row>, crate::Error> {
        Ok(tokio_postgres::Client::query(self, sql, params).await?)
    }

    async fn execute<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> Result<u64, crate::Error> {
        Ok(tokio_postgres::Client::execute(self, sql, params).await?)
    }

    async fn query_stream<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> Result<RowStream, crate::Error> {
        let rows = tokio_postgres::Client::query_raw(self, sql, slice_iter(params)).await?;
        Ok(RowStream::new(rows))
    }

    async fn copy_in<'a, I>(
        &'a self,
        describe_sql: &'a str,
        copy_sql: &'a str,
        rows: I,
    ) -> Result<u64, crate::Error>
    where
        I: Iterator<Item = Result<CopyRow, crate::Error>> + Send + 'a,
    {
        let types = column_types(&tokio_postgres::Client::prepare(self, describe_sql).await?);
        let sink = tokio_postgres::Client::copy_in(self, copy_sql).await?;
        write_rows(sink, &types, rows).await
    }
}

impl Executor for tokio_postgres::Transaction<'_> {
    async fn query<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> Result<Vec<Row>, crate::Error> {
        Ok(tokio_postgres::Transaction::query(self, sql, params).await?)
    }

    async fn execute<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> Result<u64, crate::Error> {
        Ok(tokio_postgres::Transaction::execute(self, sql, params).await?)
    }

    async fn query_stream<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> Result<RowStream, crate::Error> {
        let rows = tokio_postgres::Transaction::query_raw(self, sql, slice_iter(params)).await?;
        Ok(RowStream::new(rows))
    }

    async fn copy_in<'a, I>(
        &'a self,
        describe_sql: &'a str,
        copy_sql: &'a str,
        rows: I,
    ) -> Result<u64, crate::Error>
    where
        I: Iterator<Item = Result<CopyRow, crate::Error>> + Send + 'a,
    {
        let types = column_types(&tokio_postgres::Transaction::prepare(self, describe_sql).await?);
        let sink = tokio_postgres::Transaction::copy_in(self, copy_sql).await?;
        write_rows(sink, &types, rows).await
    }
}

/// `params` as the `query_raw` argument iterator.
pub(crate) fn slice_iter<'a>(
    params: &'a [&'a (dyn ToSql + Sync)],
) -> impl ExactSizeIterator<Item = &'a dyn ToSql> + 'a {
    params.iter().map(|p| *p as &dyn ToSql)
}
