[package]
name = "typedpg_e2e"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
typedpg = { path = "../typedpg" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
rust_decimal = { version = "1", features = ["db-tokio-postgres"] }
pgvector = { version = "0.4", features = ["postgres"] }

[dev-dependencies]
typedpg_core = { path = "../typedpg_core" }
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-serde_json-1", "with-chrono-0_4", "with-uuid-1"] }
deadpool-postgres = "0.14"
testcontainers = "0.28"
testcontainers-modules = { version = "0.15", features = ["postgres"] }
libc = "0.2"

[package.metadata.typedpg.database]
migrations = "./migrations"

[package.metadata.typedpg.types]
user_preferences = "::typedpg_e2e::UserPreferences"
post_status = "::typedpg_e2e::PostStatus"
"public.geo_point" = "::typedpg_e2e::GeoPoint"
