//! The encoding pairs each built-in conversion function accepts.
//!
//! `CREATE CONVERSION` calls the function once on an empty string, and the C
//! function rejects encodings it doesn't implement (`CHECK_ENCODING_CONVERSION_ARGS`,
//! or the ISO 8859 / WIN family lookups). The analyzer can't run the C code,
//! so this table records, per `pg_catalog` conversion function, the
//! `(source, destination)` pairs PG 18 accepts. It was derived by running
//! `CREATE CONVERSION` on a live PG 18 for every conversion function and every
//! pair of non-`SQL_ASCII` encodings (141,204 attempts, 128 accepted); the
//! error rule in [`super::conversions`] reproduces every rejection message
//! of that run.

/// `pg_encoding` ids, as named by `pg_encoding_to_char`.
pub(super) const ENCODING_IDS: &[(&str, u32)] = &[
    ("SQL_ASCII", 0),
    ("EUC_JP", 1),
    ("EUC_CN", 2),
    ("EUC_KR", 3),
    ("EUC_TW", 4),
    ("EUC_JIS_2004", 5),
    ("UTF8", 6),
    ("MULE_INTERNAL", 7),
    ("LATIN1", 8),
    ("LATIN2", 9),
    ("LATIN3", 10),
    ("LATIN4", 11),
    ("LATIN5", 12),
    ("LATIN6", 13),
    ("LATIN7", 14),
    ("LATIN8", 15),
    ("LATIN9", 16),
    ("LATIN10", 17),
    ("WIN1256", 18),
    ("WIN1258", 19),
    ("WIN866", 20),
    ("WIN874", 21),
    ("KOI8R", 22),
    ("WIN1251", 23),
    ("WIN1252", 24),
    ("ISO_8859_5", 25),
    ("ISO_8859_6", 26),
    ("ISO_8859_7", 27),
    ("ISO_8859_8", 28),
    ("WIN1250", 29),
    ("WIN1253", 30),
    ("WIN1254", 31),
    ("WIN1255", 32),
    ("WIN1257", 33),
    ("KOI8U", 34),
    ("SJIS", 35),
    ("BIG5", 36),
    ("GBK", 37),
    ("UHC", 38),
    ("GB18030", 39),
    ("JOHAB", 40),
    ("SHIFT_JIS_2004", 41),
];

/// Built-in conversion function → the `(source, destination)` pairs it accepts.
pub(super) const ACCEPTED_PAIRS: &[(&str, &[(&str, &str)])] = &[
    ("big5_to_euc_tw", &[("BIG5", "EUC_TW")]),
    ("big5_to_mic", &[("BIG5", "MULE_INTERNAL")]),
    ("big5_to_utf8", &[("BIG5", "UTF8")]),
    ("euc_cn_to_mic", &[("EUC_CN", "MULE_INTERNAL")]),
    ("euc_cn_to_utf8", &[("EUC_CN", "UTF8")]),
    (
        "euc_jis_2004_to_shift_jis_2004",
        &[("EUC_JIS_2004", "SHIFT_JIS_2004")],
    ),
    ("euc_jis_2004_to_utf8", &[("EUC_JIS_2004", "UTF8")]),
    ("euc_jp_to_mic", &[("EUC_JP", "MULE_INTERNAL")]),
    ("euc_jp_to_sjis", &[("EUC_JP", "SJIS")]),
    ("euc_jp_to_utf8", &[("EUC_JP", "UTF8")]),
    ("euc_kr_to_mic", &[("EUC_KR", "MULE_INTERNAL")]),
    ("euc_kr_to_utf8", &[("EUC_KR", "UTF8")]),
    ("euc_tw_to_big5", &[("EUC_TW", "BIG5")]),
    ("euc_tw_to_mic", &[("EUC_TW", "MULE_INTERNAL")]),
    ("euc_tw_to_utf8", &[("EUC_TW", "UTF8")]),
    ("gb18030_to_utf8", &[("GB18030", "UTF8")]),
    ("gbk_to_utf8", &[("GBK", "UTF8")]),
    ("iso8859_1_to_utf8", &[("LATIN1", "UTF8")]),
    (
        "iso8859_to_utf8",
        &[
            ("ISO_8859_5", "UTF8"),
            ("ISO_8859_6", "UTF8"),
            ("ISO_8859_7", "UTF8"),
            ("ISO_8859_8", "UTF8"),
            ("LATIN10", "UTF8"),
            ("LATIN2", "UTF8"),
            ("LATIN3", "UTF8"),
            ("LATIN4", "UTF8"),
            ("LATIN5", "UTF8"),
            ("LATIN6", "UTF8"),
            ("LATIN7", "UTF8"),
            ("LATIN8", "UTF8"),
            ("LATIN9", "UTF8"),
        ],
    ),
    ("iso_to_koi8r", &[("ISO_8859_5", "KOI8R")]),
    ("iso_to_mic", &[("ISO_8859_5", "MULE_INTERNAL")]),
    ("iso_to_win1251", &[("ISO_8859_5", "WIN1251")]),
    ("iso_to_win866", &[("ISO_8859_5", "WIN866")]),
    ("johab_to_utf8", &[("JOHAB", "UTF8")]),
    ("koi8r_to_iso", &[("KOI8R", "ISO_8859_5")]),
    ("koi8r_to_mic", &[("KOI8R", "MULE_INTERNAL")]),
    ("koi8r_to_utf8", &[("KOI8R", "UTF8")]),
    ("koi8r_to_win1251", &[("KOI8R", "WIN1251")]),
    ("koi8r_to_win866", &[("KOI8R", "WIN866")]),
    ("koi8u_to_utf8", &[("KOI8U", "UTF8")]),
    ("latin1_to_mic", &[("LATIN1", "MULE_INTERNAL")]),
    ("latin2_to_mic", &[("LATIN2", "MULE_INTERNAL")]),
    ("latin2_to_win1250", &[("LATIN2", "WIN1250")]),
    ("latin3_to_mic", &[("LATIN3", "MULE_INTERNAL")]),
    ("latin4_to_mic", &[("LATIN4", "MULE_INTERNAL")]),
    ("mic_to_big5", &[("MULE_INTERNAL", "BIG5")]),
    ("mic_to_euc_cn", &[("MULE_INTERNAL", "EUC_CN")]),
    ("mic_to_euc_jp", &[("MULE_INTERNAL", "EUC_JP")]),
    ("mic_to_euc_kr", &[("MULE_INTERNAL", "EUC_KR")]),
    ("mic_to_euc_tw", &[("MULE_INTERNAL", "EUC_TW")]),
    ("mic_to_iso", &[("MULE_INTERNAL", "ISO_8859_5")]),
    ("mic_to_koi8r", &[("MULE_INTERNAL", "KOI8R")]),
    ("mic_to_latin1", &[("MULE_INTERNAL", "LATIN1")]),
    ("mic_to_latin2", &[("MULE_INTERNAL", "LATIN2")]),
    ("mic_to_latin3", &[("MULE_INTERNAL", "LATIN3")]),
    ("mic_to_latin4", &[("MULE_INTERNAL", "LATIN4")]),
    ("mic_to_sjis", &[("MULE_INTERNAL", "SJIS")]),
    ("mic_to_win1250", &[("MULE_INTERNAL", "WIN1250")]),
    ("mic_to_win1251", &[("MULE_INTERNAL", "WIN1251")]),
    ("mic_to_win866", &[("MULE_INTERNAL", "WIN866")]),
    (
        "shift_jis_2004_to_euc_jis_2004",
        &[("SHIFT_JIS_2004", "EUC_JIS_2004")],
    ),
    ("shift_jis_2004_to_utf8", &[("SHIFT_JIS_2004", "UTF8")]),
    ("sjis_to_euc_jp", &[("SJIS", "EUC_JP")]),
    ("sjis_to_mic", &[("SJIS", "MULE_INTERNAL")]),
    ("sjis_to_utf8", &[("SJIS", "UTF8")]),
    ("uhc_to_utf8", &[("UHC", "UTF8")]),
    ("utf8_to_big5", &[("UTF8", "BIG5")]),
    ("utf8_to_euc_cn", &[("UTF8", "EUC_CN")]),
    ("utf8_to_euc_jis_2004", &[("UTF8", "EUC_JIS_2004")]),
    ("utf8_to_euc_jp", &[("UTF8", "EUC_JP")]),
    ("utf8_to_euc_kr", &[("UTF8", "EUC_KR")]),
    ("utf8_to_euc_tw", &[("UTF8", "EUC_TW")]),
    ("utf8_to_gb18030", &[("UTF8", "GB18030")]),
    ("utf8_to_gbk", &[("UTF8", "GBK")]),
    (
        "utf8_to_iso8859",
        &[
            ("UTF8", "ISO_8859_5"),
            ("UTF8", "ISO_8859_6"),
            ("UTF8", "ISO_8859_7"),
            ("UTF8", "ISO_8859_8"),
            ("UTF8", "LATIN10"),
            ("UTF8", "LATIN2"),
            ("UTF8", "LATIN3"),
            ("UTF8", "LATIN4"),
            ("UTF8", "LATIN5"),
            ("UTF8", "LATIN6"),
            ("UTF8", "LATIN7"),
            ("UTF8", "LATIN8"),
            ("UTF8", "LATIN9"),
        ],
    ),
    ("utf8_to_iso8859_1", &[("UTF8", "LATIN1")]),
    ("utf8_to_johab", &[("UTF8", "JOHAB")]),
    ("utf8_to_koi8r", &[("UTF8", "KOI8R")]),
    ("utf8_to_koi8u", &[("UTF8", "KOI8U")]),
    ("utf8_to_shift_jis_2004", &[("UTF8", "SHIFT_JIS_2004")]),
    ("utf8_to_sjis", &[("UTF8", "SJIS")]),
    ("utf8_to_uhc", &[("UTF8", "UHC")]),
    (
        "utf8_to_win",
        &[
            ("UTF8", "WIN1250"),
            ("UTF8", "WIN1251"),
            ("UTF8", "WIN1252"),
            ("UTF8", "WIN1253"),
            ("UTF8", "WIN1254"),
            ("UTF8", "WIN1255"),
            ("UTF8", "WIN1256"),
            ("UTF8", "WIN1257"),
            ("UTF8", "WIN1258"),
            ("UTF8", "WIN866"),
            ("UTF8", "WIN874"),
        ],
    ),
    ("win1250_to_latin2", &[("WIN1250", "LATIN2")]),
    ("win1250_to_mic", &[("WIN1250", "MULE_INTERNAL")]),
    ("win1251_to_iso", &[("WIN1251", "ISO_8859_5")]),
    ("win1251_to_koi8r", &[("WIN1251", "KOI8R")]),
    ("win1251_to_mic", &[("WIN1251", "MULE_INTERNAL")]),
    ("win1251_to_win866", &[("WIN1251", "WIN866")]),
    ("win866_to_iso", &[("WIN866", "ISO_8859_5")]),
    ("win866_to_koi8r", &[("WIN866", "KOI8R")]),
    ("win866_to_mic", &[("WIN866", "MULE_INTERNAL")]),
    ("win866_to_win1251", &[("WIN866", "WIN1251")]),
    (
        "win_to_utf8",
        &[
            ("WIN1250", "UTF8"),
            ("WIN1251", "UTF8"),
            ("WIN1252", "UTF8"),
            ("WIN1253", "UTF8"),
            ("WIN1254", "UTF8"),
            ("WIN1255", "UTF8"),
            ("WIN1256", "UTF8"),
            ("WIN1257", "UTF8"),
            ("WIN1258", "UTF8"),
            ("WIN866", "UTF8"),
            ("WIN874", "UTF8"),
        ],
    ),
];
